Fix for #2889 Tax calculation issue after changing Tax percent
opensourcepos/opensourcepos pull request #2950
Opened 2020-09-13 01:10 UTC by SteveIreland

This resolves issue #2889.  Document reprint was retrieving current tax rates instead of retrieving the tax rates that were applied to the original sale.

2020-09-18 15:02 UTC, jekkos approved these changes

2020-09-18 15:02 UTC, jekkos commented on application/models/Sale.php
> +		$this->db->select('item_id, name, percent');
Are we selecting all the fields here? In that case we might just omit this line.

2020-09-18 15:38 UTC, jekkos requested changes

2020-09-18 15:38 UTC, jekkos commented on application/models/Sale.php
> +		$this->db->select('item_id, name, percent');
Not sure if it's an issue, but the get_info selects all fields while this one only three.. If I recall correctly the receipt will be loaded using some tax info (if the feature is enabled). So it might be safer to just select all fields in the table to be consistent with the `get_info`

2020-09-18 23:11 UTC, SteveIreland commented on application/models/Sale.php
> +		$this->db->select('item_id, name, percent');
The get_info selects item_id, name, and percent from the Item_taxes table ... which is exactly why I limited this to the same 3 fields, so that there wouldn't be any accidental introduction of issues caused by the returned results from the two calls being different.

2020-09-19 12:13 UTC, jekkos commented on application/models/Sale.php
> +		$this->db->select('item_id, name, percent');
Ok then I might have missed that, I had the impression that it was selecting all fields. In that case we should be good. Let's also do a smoke test on the receipt with tax details enabled to see if everything renders fine.

2020-09-19 12:13 UTC, jekkos approved these changes

2020-09-19 12:14 UTC, merged

2020-09-19 13:40 UTC, SteveIreland commented on application/models/Sale.php
> +		$this->db->select('item_id, name, percent');
Okay - will do.

On another note, I was focused on the "basic tax" system which I'm assuming is still over 95% of your user base.   It never even occurred to me to test the destination based tax document reprint (until this morning while I was in the shower).  So I'll also follow up on that.