Correct issues with cash rounding.
opensourcepos/opensourcepos pull request #3026
Opened 2020-11-22 19:05 UTC by SteveIreland

This is a trial run for feedback and to see if it will build.  @odiea pointed out that this could impact cashups but that is not an area I'm familiar with.  There is still an open question regarding Summary reporting (do I need to do something with those reports). The detail reports should be properly reflecting cash rounding.

2020-11-25 19:59 UTC, jekkos commented on application/controllers/Sales.php
> +				$this->sale_lib->add_payment($payment_type, $amount_tendered, 0);
maybe use the constants here as well?

2020-11-25 19:59 UTC, jekkos commented on application/controllers/Sales.php
> +				$this->sale_lib->add_payment($payment_type, $amount_tendered, CASH_ADJUSTMENT_FALSE);
the defautl is false I suppose? Maybe we can just specify that in the method itself as a default parameter value or would you prefer to set it automatically

2020-11-25 19:59 UTC, jekkos commented on application/migrations/20201108100000_cashrounding.php
> +		$this->db->query('ALTER TABLE ' . $this->db->dbprefix('sales_payments') . ' ADD COLUMN `cash_adjustment` tinyint NOT NULL DEFAULT 0 AFTER `cash_refund`');
Do we need to backfill this field for existing sales in some way?

2020-11-25 19:59 UTC, jekkos commented on application/models/Sale.php
> +			$sale_total = 'ROUND(SUM(' . $sale_price . '), ' . $decimals . ') - ' . $cash_adjustment;
so the adjustment is already saved as rounded amount? What if the precision changes? It might be better to save as much detail as possible and round here in the end?

2020-11-25 19:59 UTC, jekkos commented on application/libraries/Sale_lib.php
> +			$totals['cash_adjustment_amount'] = round($totals['total'] - $totals['payment_total'], totals_decimals(), PHP_ROUND_HALF_UP);
Ok so we do the rounding here and then save it in the db

2020-11-25 19:59 UTC, jekkos commented on application/controllers/Sales.php
> +			$this->session->set_userdata('cash_adjustment_amount', $totals['amount_due'] - $totals['cash_amount_due']);
any reason to use a session variable for this one?

2020-11-25 19:59 UTC, jekkos commented on application/libraries/Sale_lib.php
> +			$totals['cash_adjustment_amount'] = 0;
you could set this one upfront (and get rid of the else statement)

2020-12-01 14:09 UTC, SteveIreland commented
The reason this isn't being resolved as quickly as I would like is because the cash adjustment payment type approach is requiring me to address a couple of new areas.  At the end of the day yesterday I had the register, the receipt, and the receipt reprint working the way I want.  The daily sales report is still looking good.  I was startled when I tested the scenario with a cash payment that required change due as well as adjusting for cash rounding.  That was an oversight on my part but has been resolved.

2020-12-02 09:47 UTC, jekkos commented
@SteveIreland indeed I think this change is a bit more involved (as it touches different parts in the app)..

2020-12-05 17:50 UTC, SteveIreland commented
I've updated this pull request with several fixes I made this morning.  But it's not ready for testing yet.  I have a problem with the "success" response not be delivered on a successful sales update and I'm checking to see if a rebuild clears that problem.  Also, I have not yet added the migration or looked to see if there is a negative impact on the cashup component.

2020-12-12 20:25 UTC, jekkos commented
Success response not showing is typically the server side that is sending a different status code (non 200)? So not sure if you were able to spot anything when you enable logging?

2020-12-13 01:06 UTC, SteveIreland commented
Thanks @jekkos, I believe I've resolved the issue with the success response.  There was an issue with one of the database updates.

2020-12-13 02:28 UTC, SteveIreland commented
Found the issue with #3041 and the next update to this pull request will include the fix for that.

2020-12-13 23:22 UTC, SteveIreland commented
This last update to this pull request also includes an attempt to address #3031.  Hopefully it works as needed.  There are so many test scenarios that could be tested but I wasn't able to get through them this weekend.

2020-12-20 20:47 UTC, truchosky commented
this will work with cash rounding -1 ? https://github.com/opensourcepos/opensourcepos/issues/2355

2020-12-28 16:56 UTC, daN4cat requested changes

2020-12-28 16:56 UTC, daN4cat commented on application/libraries/Sale_lib.php
> +				$this->CI->session->set_userdata('cash_mode', 0);
Should cash_mode values defined instead of using magic numbers?

2020-12-28 16:57 UTC, daN4cat commented
Was this change tested in any way outside Steve's run? @odiea ?

2020-12-28 16:57 UTC, daN4cat commented
@jekkos is this the last to close 3.3.3?

2020-12-28 20:05 UTC, jekkos commented
I have moved to 3.3.4 for now.

2021-01-03 23:02 UTC, SteveIreland commented
@truchosky I will test this week to make sure that -1 still works, but I'm pretty sure it will.

2021-01-10 19:25 UTC, SteveIreland commented on application/libraries/Sale_lib.php
> +				$this->CI->session->set_userdata('cash_mode', 0);
That correction has been made.

2021-01-10 20:14 UTC, daN4cat requested changes

2021-01-10 20:14 UTC, daN4cat commented on application/controllers/Sales.php
> +				$cash_adjustment = 1;
Is this supposed to be 1 or one of the defines? Same comment for the 0 case below.

2021-01-10 20:14 UTC, daN4cat commented on application/controllers/Sales.php
> +				$cash_adjustment = 1;
Same comment 1 or a define? Same applies for the case 0 below.

2021-01-10 20:14 UTC, daN4cat commented on application/views/sales/register.php
> +	else if(($("#payment_types").val() == "<?php echo $this->lang->line('sales_cash'); ?>" && cash_mode == '1'))
should the '1' be one of the defines?

2021-01-10 21:20 UTC, SteveIreland commented on application/views/sales/register.php
> +	else if(($("#payment_types").val() == "<?php echo $this->lang->line('sales_cash'); ?>" && cash_mode == '1'))
I didn't touch this one because it falls into the JavaScript territory.  I didn't see any precedence of magic names in JavaScript that I could replicate and I didn't want to start a new tradition without direction.  :-)

2021-01-10 22:28 UTC, daN4cat commented on application/views/sales/register.php
> +	else if(($("#payment_types").val() == "<?php echo $this->lang->line('sales_cash'); ?>" && cash_mode == '1'))
You are correct

2021-01-17 13:41 UTC, odiea commented
@SteveIreland is there any reason that you remove the column cash_rounding in the migration script. After it is removed there is a db error completing the sale

2021-01-17 14:43 UTC, odiea commented
I was incorrect. Apparently the migration script did not run so I had to manually add that row.

2021-01-18 22:09 UTC, jekkos commented
@SteveIreland any update on what the state is here? Do you know if it is bug free or do you need support with anything? Thanks!

2021-01-26 07:49 UTC, objecttothis commented
@SteveIreland @jekkos How close are we to merging this? Are you stuck and need help?

2021-01-26 11:45 UTC, objecttothis requested changes
Great work @SteveIreland.  See my comments.

2021-01-26 11:45 UTC, objecttothis commented on application/libraries/Sale_lib.php
> +		if($cash_rounding)
Can we add a blank line between 430 and 431 for readability?

2021-01-26 11:45 UTC, objecttothis commented on application/libraries/Sale_lib.php
> +			if($decoded_payment_id == $this->CI->lang->line('sales_cash_adjustment'))
The current code logic will always run even if the prior if statement is true.  Is that what we want?  I can't quite tell but it appears that the second if statement will never evaluate to true if the first evaluates to true, so we can replace it with elseif which will cause PHP to skip it and save the processing time.  Thoughts?

2021-01-26 11:45 UTC, objecttothis commented on application/libraries/Sale_lib.php
> +	 * 'subtotal', 'discounted_subtotal', 'tax_exclusive_subtotal', 'item_count', 'total_units', 'cash_adjustment_amount'
Two thoughts.
1- If we document this, we should try to use a PHPdoc format.  I'm not sure what we have agreed on for this project (https://docstore.mik.ua/orelly/webprog/pcook/ch21_09.htm)
2- From a clean coding perspective, one of the pitfalls associated with these kinds of comments is that they can accidentally be misleading.  For example if a code contributor changes what the function returns for a good reason, but then doesn't update this list, another code contributor might look at this list to see what the function returns not knowing that the information in it is stale.  It might be better to instead document as 

`@return    array    Values needed for calculating payments in sales`

Or something similar to that.  Then in the code, as much as possible, group the associative array assignments together.

2021-01-26 11:45 UTC, objecttothis commented on application/libraries/Sale_lib.php
> +			foreach($this->CI->Sale->get_sale_payments($sale_id)->result() as $row)
Blank line needed between 1066 and 1067 for readability.

2021-01-26 11:45 UTC, objecttothis commented on application/libraries/Sale_lib.php
> +			if($cash_types_only)
Blank line needed between 1074 and 1075 for readability

2021-01-26 11:45 UTC, objecttothis commented on application/libraries/Sale_lib.php
> +	 * It also set resets the cash mode to disabled which will then be re-evaluated when
From a clean coding perspective, functions should do one thing as much as possible.  There may be risk in having one function both determine whether cash rounding should be used on the site AND reset the cash mode to disabled but then call the function "reset_cash_rounding".  Food for thought... Perhaps @jekkos or @daN4cat have an opinion.

2021-01-26 11:45 UTC, objecttothis commented on application/libraries/Sale_lib.php
> +			if($cash_mode)
rather than nesting an if statement inside another if statement, it might be better to combine the two

`if($include_cash_rounding && $cash_mode)`

2021-01-26 11:45 UTC, objecttothis commented on application/models/Sale.php
> +		$sale_total = 'ROUND(SUM(' . $sale_price . '), ' . $decimals . ') + ' . $sales_tax . ' + ' . $cash_adjustment;
Rather than using the concatenation operator (.), this is a great place to instead use the PHP parser by replacing ' with " and ditching the concatination.  165 becomes

`$sale_total = "ROUND(SUM($sale_price)), $decimals) + $sales_tax + $cash_adjustment";` 

IMO is much more readable.  Thoughts?  You might also change 164 and other lines to do the same thing.

2021-01-26 11:45 UTC, objecttothis commented on application/models/Sale.php
> +		$sale_total = 'ROUND(SUM(' . $sale_price . '), ' . $decimals . ') + ' . $sales_tax . ' + ' . $cash_adjustment;
You're doing it in line 211 as an example if that helps.

2021-01-26 11:45 UTC, objecttothis commented on application/models/Sale.php
> +						'sale_id'		  => $sale_id,
I personally love using the tab to line up all the `=>` operators and wish that we could do it everywhere.  What I'm finding is that unfortunately various IDEs don't render the tabs properly and they end up looking like garbage.  It pains me to say but we should probably stick to single spaces before and after the `=>` operators rather than tabs before and single space after.  Thoughts?

2021-01-26 11:45 UTC, objecttothis commented on application/models/Sale.php
> +			$sale_total = 'ROUND(SUM(' . $sale_price . '), ' . $decimals . ') + ' . $cash_adjustment;
Same as my earlier comment about using the PHP parser instead of concatenation operator.

2021-01-26 11:45 UTC, objecttothis commented on application/models/Sale.php
> +			$sale_subtotal = 'ROUND(SUM(' . $sale_price . '), ' . $decimals . ') - ' . $internal_tax . ' + ' . $cash_adjustment;
Here too.

2021-02-02 13:00 UTC, objecttothis commented
@jekkos @daN4cat I'm starting on this today.  I got a bit of a late start.  I'll begin with my code review, then resolve the other code review comments and begin testing against the issues list to make sure this fixes all of those bugs.

2021-02-03 20:27 UTC, jekkos commented on application/controllers/Sales.php
> +define('CASH_ADJUSTMENT_TRUE', 1);
Ok yes let's keep it in one place for now. Ideally we separate it out further later on..

2021-02-04 02:15 UTC, SteveIreland commented on application/controllers/Sales.php
> +			elseif($payment_type == $this->lang->line('sales_cash'))
I changed it to use the identical and not identical operators for comparisons involving payment type.   And didn't take it any further lest things start breaking.

2021-02-04 02:17 UTC, SteveIreland commented on application/controllers/Sales.php
> +		if($data['cash_mode'] && ($data['selected_payment_type'] == $this->lang->line('sales_cash') || $data['payments_total'] > 0))
done

2021-02-04 02:18 UTC, SteveIreland commented on application/controllers/Sales.php
> +		// cash_rounding indicates only that the site is configured for cash rounding
done

2021-02-04 02:21 UTC, SteveIreland commented on application/libraries/Sale_lib.php
> +			if($cash_mode)
done

2021-02-04 02:25 UTC, SteveIreland commented on application/models/Sale.php
> +						'sale_id'		  => $sale_id,
I would prefer not to spend time time fussing with tabs to line things up but I am good either way.

However, that's a decision that's above my pay grade.

2021-02-04 05:01 UTC, objecttothis commented on application/models/Sale.php
> +						'sale_id'		  => $sale_id,
To clarify, my understanding of the project practice is that we aren't worrying about adding tabs left and right of the => operator.  Just tabs left of the line being important.

2021-02-05 02:55 UTC, SteveIreland commented on application/models/Sale.php
> +						'sale_id'		  => $sale_id,
I recall being asked once to line them up, but that was years ago.  Things change.

2021-02-05 03:01 UTC, SteveIreland commented on application/controllers/Sales.php
> +		// cash_mode indicates whether this sale is going to be processed using cash_rounding
There were a handful in Sales.php that weren't preceded by a blank line, so I "fixed" them all.  however, if it was preceded by an open or close brace then I figured that was close enough to a blank line.

2021-02-05 06:46 UTC, objecttothis commented on application/models/Sale.php
> +						'sale_id'		  => $sale_id,
@jekkos @daN4cat What do you want to do here?  Do we align the left side of the => operators with tabs or have a space on either side.  Aligning with tabs looks better IMO, but it doesn't always render lined up on all IDEs.  I've seen both in the code, but consistency is probably important.

2021-02-05 09:10 UTC, daN4cat commented on application/models/Sale.php
> +						'sale_id'		  => $sale_id,
Let's not get too bothered about this detail. It's fine like it is, there are plenty of other examples where on this specific case we followed different approaches.
If one day I have time to do some cosmetic work, I'll give a pass to everything.

2021-02-05 09:57 UTC, objecttothis commented on application/models/Sale.php
> +						'sale_id'		  => $sale_id,
OK

2021-02-05 10:01 UTC, objecttothis approved these changes
Looks like that's everything. @SteveIreland I think you said that the PR already resolves the issues that it set out to.

2021-02-07 18:55 UTC, SteveIreland commented
After some testing to make sure that I didn't fat finger the corrections, I've pushed it back up. But there is still an issue with correcting payments if the user does something odd like making a partial cash payment against an invoice and then enters a subsequent credit card payment (which should invalidate the cash adjustment).  However, the payment adjustment functionality isn't currently robust enough to handle that scenario.  I believe I'd still like to get this pull request merged and then I'll follow up with another change to improve the payment adjustment to handle the odd scenario (rather than dragging this change out any longer).

2021-02-07 18:59 UTC, objecttothis commented
> After some testing to make sure that I didn't fat finger the corrections, I've pushed it back up. But there is still an issue with correcting payments if the user does something odd like making a partial cash payment against an invoice and then enters a subsequent credit card payment (which should invalidate the cash adjustment). However, the payment adjustment functionality isn't currently robust enough to handle that scenario. I believe I'd still like to get this pull request merged and then I'll follow up with another change to improve the payment adjustment to handle the odd scenario (rather than dragging this change out any longer).


Agreed. It seems like making it more robust falls more in the category of enhancement than bugfix.

2021-02-07 19:12 UTC, SteveIreland commented
Okay, I have a travis-ci issue and I'm in deeper water than I'm used to.  I can't find anything that is code related and what I can find suggests that it's a permission issue.  Can someone provide some insight?  Is this related to travis-ci shutting down soon?

2021-02-07 20:22 UTC, objecttothis commented
> 
> 
> Okay, I have a travis-ci issue and I'm in deeper water than I'm used to. I can't find anything that is code related and what I can find suggests that it's a permission issue. Can someone provide some insight? Is this related to travis-ci shutting down soon?

This seems to indicate that the build passed (https://travis-ci.org/github/opensourcepos/opensourcepos/builds/757954759).  What exactly is the issue that's happening?

2021-02-07 23:19 UTC, SteveIreland commented
Okay, something changed and it was restarted and completed.  I am NOT insane.  I know there was an issue.  I knew I should have taken an image of the screen.  Someone is gas-lighting me.  :-)  

I'm ready to merge unless someone objects to this.

2021-02-08 05:26 UTC, objecttothis commented
> I'm ready to merge unless someone objects to this.

@SteveIreland I see what you did there. ;) Merge away!

2021-02-08 10:18 UTC, jekkos commented
> > Okay, I have a travis-ci issue and I'm in deeper water than I'm used to. I can't find anything that is code related and what I can find suggests that it's a permission issue. Can someone provide some insight? Is this related to travis-ci shutting down soon?
> 
> This seems to indicate that the build passed (https://travis-ci.org/github/opensourcepos/opensourcepos/builds/757954759). What exactly is the issue that's happening?

I have restarted the build and it went fine after.. there is a rate limitation on docker hub usage and it seems to kick in now and then..

2021-02-08 13:26 UTC, merged