Add SameSite=Strict attribute (#1980)
opensourcepos/opensourcepos pull request #3047
Opened 2020-12-18 10:23 UTC by jekkos

Added an override of the csrf token generation that includes SameSIte flag. Checked locally and indeed this attribute is being set on the cookie now.

2020-12-18 10:33 UTC, objecttothis commented
Is this related to #1498 and #1980?

2020-12-18 10:38 UTC, objecttothis requested changes
Just the two minor formatting changes.  I haven't had a chance to download the build and test it, but I assume that you've done that.

2020-12-18 10:38 UTC, objecttothis commented on application/core/MY_Security.php
> +        if ($secure_cookie && !is_https()) {
I believe we decided on the standard of having curly braces { on their own line.

2020-12-18 10:38 UTC, objecttothis commented on application/core/MY_Security.php
> +
I would remove this blank line.

2020-12-18 10:47 UTC, jekkos commented on application/core/MY_Security.php
> +        if ($secure_cookie && !is_https()) {
fixed

2020-12-18 10:48 UTC, jekkos commented on application/core/MY_Security.php
> +
done

2020-12-18 10:50 UTC, jekkos commented
@objecttothis indeed. I have enabled HTTPOnly flag by default now for the session id. This is a flag that can be set per cookie. I think this should make JS based exploits quite a bit harder as we only leave the csrf cookie value readable by Javascript.

Also the latter now carries SameSite flag, which means that it won't be posted to any external attacker domain in case a XSS exploit is possible.

2020-12-18 10:58 UTC, jekkos commented on application/core/MY_Security.php
> +                'httponly' => FALSE]);
@objecttothis  so in this case we have no choice but to set httpOnly to false (we need to read this value in JS in order to post it back  using AJAX). However we do have SameSite security now (so we won't leak this token to other domains)

2020-12-18 11:24 UTC, objecttothis commented on application/core/MY_Security.php
> +                'httponly' => FALSE]);
Understood.  My understanding is that the attack vector would be limited to malicious code installed on the same domain then.  That is still definitely a possibility but much better than an attack vector open from all domains.  In terms of #1498 we would need to figure out another way to do CSRF with AJAX, so let's keep that ticket open but close #1980 with this one then.

2020-12-18 11:26 UTC, objecttothis requested changes

2020-12-18 11:26 UTC, objecttothis commented on application/config/config.php
> +$config['cookie_httponly'] = TRUE;
Did you mean to push this commit?  Doesn't this break AJAX?

2020-12-18 12:38 UTC, jekkos commented on application/config/config.php
> +$config['cookie_httponly'] = TRUE;
Yes, this can be set to true now and will only be applied to the php session id

@objecttothis indeed. I have enabled HTTPOnly flag by default now for the session id. This is a flag that can be set per cookie. I think this should make JS based exploits quite a bit harder as we only leave the csrf cookie value readable by Javascript.

2020-12-18 13:45 UTC, objecttothis approved these changes

2020-12-18 13:49 UTC, objecttothis commented
@daN4cat perhaps this allows you to re-enable CSRF check on the login? #1535

2020-12-18 13:51 UTC, objecttothis commented on application/config/config.php
> +$config['cookie_httponly'] = TRUE;
@jekkos should we attach #1498 to this and close it then, or leave it as a placeholder reminder to figure out how to get AJAX and CSRF to place nice together?

2020-12-18 16:23 UTC, odiea commented
With error on I received the following. I changed config and added my security to the bower update download. Did I miss something?
A PHP Error was encountered
Severity: Warning

Message: setcookie() expects parameter 3 to be integer, array given

Filename: core/MY_Security.php

Line Number: 24
Backtrace:
File: C:\wamp64\www\bowerup\application\core\MY_Security.php
Line: 24
Function: setcookie
File: C:\wamp64\www\bowerup\public\index.php
Line: 315
Function: require_once

2020-12-18 23:24 UTC, odiea commented
This requires php 7.3 to work as an addon.

2020-12-19 14:04 UTC, odiea commented
To get my current branch to work and not show errors with PHP 7.2 and also works in 7.3. As per PHP manual.
```
setcookie($this->_csrf_cookie_name,
            $this->_csrf_hash,(int)
            ['samesite' => 'Strict',
            ['secure' => $secure_cookie,
            ['expires' => $expire,
            ['path' => config_item('cookie_path'),
            ['domain' => config_item('cookie_domain'),
            ['httponly' => FALSE]]]]]]);
```

2020-12-20 11:04 UTC, jekkos commented
Indeed it seems that there are two versions of the setcookie() function in PHP. The one we use now is only available in PHP 7.3. Good job spotting that.

Bottom line is that this SameSite will only work with the newer version of this function, as only that one allows you to set cookie attributes using an array. The older version does not offer a boolean flag to set this property, so if we want to support 7.2 we will need to find a workaround here.

I guess we were fine bumping the minimum version to 7.1. Not sure if we can agree to push this to 7.3 for this issue alone.

2020-12-20 11:15 UTC, daN4cat commented
7.1 as 5.6 are deprecated.

2020-12-20 11:29 UTC, jekkos commented
Ok indeed so let's stick with 7.2 as a minimum then. I have added  a workaround for the issue now. As there is no one size fits all solution a version detection is needed. The 7.4 version does not seem to allow the trick of adding an extra attribute after the path. According to the stackoverflow post it should work for 7.2 but can't test that for now.

2020-12-20 11:29 UTC, jekkos commented on application/core/MY_Security.php
> +            setcookie($this->_csrf_cookie_name,
@odiea we run the old function version in case we're on a version older than 7.3 here

2020-12-20 11:37 UTC, jekkos commented
Ok I do see the warning in FF that setting SameSite does not make sense if Secure flag for the cookie is not set. We can thus only set it in case we are on HTTPS. I sugges to set SECURE flag to true in case we are on HTTPS and then together with that the SameSite. Adaptations for this are done in the last commit. I still need to test on HTTPS but basically most of the security improvements should be activated automatically if SSL is setup.

2020-12-21 16:05 UTC, jekkos commented on application/core/MY_Security.php
> +            setcookie($this->_csrf_cookie_name,
If you find some opportunity to test, let me know. Otherwise let's proceed and merge.

2020-12-22 10:44 UTC, jekkos commented on application/config/config.php
> +$config['cookie_httponly'] = TRUE;
I think indeed that issue can be closed, we enable httpOnly for all cookies except the CSRF token.. I think it's a fairly strong security improvement.

2020-12-23 13:09 UTC, jekkos commented
@daN4cat woops I also updated the install instructions here

2020-12-23 15:43 UTC, daN4cat commented
Oh well....

2020-12-25 21:20 UTC, merged