Use longblob for session data storage (#3006)
opensourcepos/opensourcepos pull request #3068
Opened 2021-01-02 21:43 UTC by jekkos

Use MEDIUMBLOB type for session data storage. This should increase the max amount of items that can be stored in a cart.

2021-01-02 22:18 UTC, daN4cat commented on application/migrations/20200819000000_modify_session_datatype.php
> +class Migration_modify_session_datatype extends CI_Migration
date of the file name is wrong, shouldn't it be 20210102000000....

2021-01-02 22:19 UTC, daN4cat requested changes
See my review comment

2021-01-02 23:09 UTC, jekkos commented on application/migrations/20200819000000_modify_session_datatype.php
> +class Migration_modify_session_datatype extends CI_Migration
Ok filename adapted.

2021-01-04 17:34 UTC, jekkos commented
@daN4cat should be good now

2021-01-04 21:58 UTC, merged