Add item_number to item kits module
opensourcepos/opensourcepos pull request #3090
Opened 2021-02-03 20:09 UTC by jekkos

This is a feature in item kits that adds an explicit item_number to the table so unique barcodes can be assigned, apart from the regular item id.

Initially I built this for a donation from someone that might just have found the build on the server and then never gave what he promised. As I just have it lying here I thought it would still be good if it benefits others (as I won't use it anyway).

2021-02-04 06:32 UTC, objecttothis requested changes

2021-02-04 06:32 UTC, objecttothis commented on application/controllers/Item_kits.php
> +
unneeded extra blank line.

2021-02-04 06:32 UTC, objecttothis commented on application/controllers/Sales.php
> +			$item_kit_id = (count($pieces) > 1)	? $pieces[1] : $item_id_or_number_or_item_kit_or_receipt;
You have a tab left of the ? instead of a single space.

2021-02-04 06:32 UTC, objecttothis commented on application/models/Item_kit.php
> +		$this->db->where('item_kit_number', (string) $item_kit_number);
I haven't been casting variables in my CI QueryBuilder function calls.  Should we be doing this everywhere or is there specific reason to do it here?

2021-02-04 06:32 UTC, objecttothis commented on application/models/Item_kit.php
> +			$this->db->where('item_kit_id !=', (int) $item_kit_id);
Same question about casting here for $item_kit_id.

2021-02-04 06:32 UTC, objecttothis commented on application/models/Item_kit.php
> +		if(ctype_digit($item_kit_id) && substr($item_kit_id, 0, 1) != '0')
For bug prevention you may want to use !== here instead of !=

2021-02-04 06:32 UTC, objecttothis commented on application/models/Item_kit.php
> +		return ($this->db->get()->num_rows() >= 1);
More of a thought than something that must be changed, but you can delete line 53 and replace this line with `return ($this->db->get('item_kits')->num_rows() >= 1);`

It saves a function call.  The downside is that it could negatively impact code readability.  I had to do it in my optimizations in the other PR because those QueryBuilder function calls were in foreach loops with thousands of calls in them (for CSV imports) and it was making significant improvement in speed.  Here maybe that won't be happening, so I don't feel strongly about it.  thoughts?

2021-02-04 06:32 UTC, objecttothis commented on application/views/item_kits/form.php
> +							'value'=>1,
Maybe I'm reading the diff wrong, but it looks like this change created a duplicate `'value'=>1,` on lines 135 and 136.  Is that intentional?

2021-02-04 06:32 UTC, objecttothis commented on application/views/item_kits/form.php
> +			category: "<?php echo $this->lang->line('items_category_required'); ?>",
I'm confused what happened here.  Is the closing bracket for messages now missing?  Should the category and item_kit_number messages be outside of the messages: block?

2021-02-08 20:44 UTC, jekkos commented on application/controllers/Item_kits.php
> +
fixed

2021-02-08 20:45 UTC, jekkos commented on application/controllers/Sales.php
> +			$item_kit_id = (count($pieces) > 1)	? $pieces[1] : $item_id_or_number_or_item_kit_or_receipt;
fixed

2021-02-08 20:46 UTC, jekkos commented on application/models/Item_kit.php
> +		$this->db->where('item_kit_number', (string) $item_kit_number);
I remember one case that needed an explicit cast. It might change the way the actual query is generated.

2021-02-08 20:47 UTC, jekkos commented on application/models/Item_kit.php
> +		$this->db->where('item_kit_number', (string) $item_kit_number);
Not sure if we should do it everywhere though.

2021-02-08 20:48 UTC, jekkos commented on application/models/Item_kit.php
> +			$this->db->where('item_kit_id !=', (int) $item_kit_id);
I cast it to int as the data column type is an int as well. I'm not sure if a correct query would be generated if this variable was a string in php (it might result in `= '123'` instead of `= 123`.

2021-02-08 20:49 UTC, jekkos commented on application/models/Item_kit.php
> +		return ($this->db->get()->num_rows() >= 1);
I like code that is more concise, so I'll change it as you propose.

2021-02-08 20:50 UTC, jekkos commented on application/views/item_kits/form.php
> +							'value'=>1,
Correct. Fixed it.

2021-02-08 20:51 UTC, jekkos commented on application/views/item_kits/form.php
> +			category: "<?php echo $this->lang->line('items_category_required'); ?>",
it's an indentation issue. Fixed now.

2021-02-08 20:53 UTC, jekkos commented
@objecttothis I have processed your remarks. I'll do a quick test locally to see if it's good and then merge if you're fine with this.

2021-02-09 11:37 UTC, objecttothis commented
Looks like Travis-CI hit the rate limiter again "docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit."

2021-02-09 16:51 UTC, jekkos commented
I guess that using these free service is nice until they get too much traction..

2021-02-09 16:53 UTC, jekkos commented on application/models/Item_kit.php
> +		return $this->db->delete('item_kits', array('item_kit_id' => $item_kit_id));
@objecttothis I think this was also a bug (item kit delete might have never worked)??

2021-02-10 07:37 UTC, objecttothis approved these changes

2021-02-10 09:27 UTC, merged