Customer tags
opensourcepos/opensourcepos pull request #3118
Opened 2021-02-27 11:50 UTC by DamianoSilverhand

@jekkos this pull request adds Customer custom fields, hereby named as Tags, with the same functionality as Item Attributes. But as of issue https://github.com/opensourcepos/opensourcepos/issues/3111#, works needs to be done on pulling the tags from the database and displaying them in the customer view.
Major changes include :

1. New Migration to include new Tags module
2. Customer CSV import and file generation refactored to include Tags.

2021-02-28 11:58 UTC, jekkos requested changes
Changeset looks good overall, I'll do a more thorough review a bit later on. We'll have to merge the work from @objecttothis first to have the import improvements. Once that is done we can polish this one up a bit and reuse some common logic (like the import validation checks).

Thanks already for the work done here.

2021-02-28 11:58 UTC, jekkos commented on application/controllers/Customers.php
> +	// 				{
Is this new code or old code commented out?

2021-02-28 11:58 UTC, jekkos commented on application/controllers/Customers.php
> +		$allowed_tags = $this->Tag->get_definition_names(FALSE);
I like the naming maybe even better then 'attributes'. However currently it's not really clear that attributes are linked to items and tags to customers from the naming only.

2021-02-28 11:58 UTC, jekkos commented on application/controllers/Customers.php
> +	// 				{
I guess this is unused so it can be removed?

2021-02-28 11:58 UTC, jekkos commented on application/controllers/Customers.php
> +							'phone_number'	=> $line['Phone Number'],
Ok good to use the key names to identify the fields here

2021-02-28 11:58 UTC, jekkos commented on application/controllers/Customers.php
> +						log_message("ERROR","CSV Item import failed on line ". $failed_row .". This customer was not imported.");
I guess we show a popup as well in the end? Should be customer import not item

2021-02-28 11:58 UTC, jekkos commented on application/controllers/Customers.php
>  					$message = $this->lang->line('customers_csv_import_partially_failed') . ' (' . count($failCodes) . '): ' . implode(', ', $failCodes);
Good idea to do the rollback in case a failure occurs

2021-02-28 11:58 UTC, jekkos commented on application/controllers/Customers.php
> +					if(in_array($tag_value, $dropdown_values) === FALSE && !empty($tag_value))
not sure if this code can be extracted / reused (as we might have similar checks now in the item import). Maybe @objecttothis after we'll merge your PR?

2021-02-28 11:58 UTC, jekkos commented on application/helpers/importcustomer_helper.php
> +function customer_bom_exists(&$file_handle)
This helper can probably be shared between item and customer import. I gues the latter will be merged first

2021-02-28 11:58 UTC, jekkos commented on application/migrations/sqlscripts/3.3.4_customer_tags.sql
> +
from a db point of view I suppose it's more simple to do it this way.. I would rename the module to sth like Customer Tags and then Attributes can be named 'Item tags' just for consistency

2021-03-01 08:47 UTC, objecttothis commented
> 
> 
> @jekkos this pull request adds Customer custom fields, hereby named as Tags, with the same functionality as Item Attributes. But as of issue #3111, works needs to be done on pulling the tags from the database and displaying them in the customer view.
> Major changes include :
> 
>     1. New Migration to include new Tags module
> 
>     2. Customer CSV import and file generation refactored to include Tags.

I haven't looked at the code yet, but a couple of thoughts on design.  All of these thoughts are IMO:
- This needs to be implemented at the person level, not just the customer level.  The reason is that you want to be able to add attributes to the Suppliers, Customers and Employees.  All of those are at the People level.  It's OK if we only do customers for now, but this needs to be designed in such a way as to allow the easy expansion to Suppliers and Employees.
- The database needs to use a separate set of definition, attribute and link tables from item attributes.
- I think we need to avoid overcomplication of naming conventions and just stick to "Item Attributes" and "People Attributes".  On the UI, they can just be called attributes and then the business logic needs to differentiate depending on whether we are working with people or items.

2021-03-01 12:54 UTC, objecttothis requested changes
For clarity, my comments are all IMO and open for discussion on them.  @jekkos and @daN4cat feel free to override them.  I feel strongly about the naming conventions, but then again, I feel strongly about most things ;)

2021-03-01 12:54 UTC, objecttothis commented on application/config/autoload.php
> +	'Tag'
We should stick with the current naming and call this person_attribute instead of tag IMO.  @jekkos @daN4cat thoughts?

2021-03-01 12:54 UTC, objecttothis commented on application/helpers/importcustomer_helper.php
> +function customer_bom_exists(&$file_handle)
Agreed.  Reduces code duplication.  The item import changes need to be imported before this PR.

2021-03-01 12:54 UTC, objecttothis commented on application/migrations/20210226124200_customer_tags.php
> +
This down function needs to be completed... I'm guessing it would just be a script that deletes these tables.

2021-03-01 12:54 UTC, objecttothis commented on application/migrations/sqlscripts/3.3.4_customer_tags.sql
> +
@jekkos I'm fine with changing attributes to tags, which would make the variable names more brief, but I would advocate that this change be implemented on the People level so that tags could later be applied to Suppliers and Employees, even if this PR only implements them for customers ATM.  I think the naming then could be people_tags and then we have a technical debt for someone to refactor attributes to item_tags.  Thoughts?

2021-03-01 12:54 UTC, objecttothis commented on application/views/tags/item.php
> +				if ($definition_value['definition_type'] == DATE)
IMO these need to be in a switch statement rather than a bunch of else if statements... if not, we need to at minimum modify this to use the === operator.

2021-03-01 13:26 UTC, DamianoSilverhand commented on application/controllers/Customers.php
> +	// 				{
@jekkos yes the commented code is the original code involved with csv import and is unused in this PR.

2021-03-01 16:21 UTC, DamianoSilverhand commented on application/controllers/Customers.php
> +		$allowed_tags = $this->Tag->get_definition_names(FALSE);
@jekkos  which naming should be implemented, should I keep the tags as they are or change to customer_tags or customer_attributes as suggested by @objecttothis ?

2021-03-01 18:37 UTC, objecttothis commented on application/controllers/Customers.php
> +		$allowed_tags = $this->Tag->get_definition_names(FALSE);
To clarify, since my position changed below after reading some of @jekkos comments.  My recommendation is to change it to person_tags:
- The naming scales well to use this in suppliers and employees.
- It's shorter than person_attributes or customer_attributes.
- We can later refactor attributes to be item_tags instead of attributes.
- The GUI everywhere should be just tags since the context will make it clear about which tags we are talking about... although we will need to think through how we want to define tags.  Once it gets scaled to employees and suppliers then just probably have a multi-select dropdown allowing you to choose which types of "person" the tag will apply to.

2021-03-01 21:58 UTC, jekkos commented on application/migrations/sqlscripts/3.3.4_customer_tags.sql
> +
If we use the person table to link the tags to then it's just a matter of running the queries in those controllers as well. I think that for this change that's enough.. Link it to the person table and then have it functional in the customer module only. If you get the database model right, you'll be able to rework and factor out the common code to use it in employees as well?

2021-03-01 22:00 UTC, jekkos commented on application/config/autoload.php
> +	'Tag'
Yes or person_tags in this case? I must say that I like the fact that it's shorter, especially if we have to identify to which module it belongs?

2021-03-02 06:52 UTC, daN4cat commented on application/config/autoload.php
> +	'Tag'
Tags tend to be used to create semantic sets, we risk of mixing up terminology.
What about leaving attribute?

2021-03-02 06:53 UTC, daN4cat commented on application/config/autoload.php
> +	'Tag'
Or person_attribute

2021-03-03 08:06 UTC, jekkos commented on application/helpers/importcustomer_helper.php
> +function customer_bom_exists(&$file_handle)
Ok we can leave this open for now, will need to be resolved once @objecttothis changes are in.

2021-03-03 08:07 UTC, jekkos commented on application/config/autoload.php
> +	'Tag'
Also fine, I mostly prefer shorter naming, but might be less correct as @daN4cat says here.

2021-03-03 08:08 UTC, jekkos commented on application/controllers/Customers.php
> +		$allowed_tags = $this->Tag->get_definition_names(FALSE);
@objecttothis are you fine to make it person_attributes as @daN4cat ? Let's make sure we're on the same page here then.

2021-03-03 13:44 UTC, objecttothis commented
Yeah that's fine. I don't have a hangup on person_tags, but person_attributes is fin with me too. We may not even need to refactor attributes to item_attributes if we go with person_attributes.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: jekkos <notifications@github.com>
Sent: Wednesday, March 3, 2021 12:08:49 PM
To: opensourcepos/opensourcepos <opensourcepos@noreply.github.com>
Cc: objecttothis <objecttothis@gmail.com>; Mention <mention@noreply.github.com>
Subject: Re: [opensourcepos/opensourcepos] Customer tags (#3118)


@jekkos commented on this pull request.

________________________________

In application/controllers/Customers.php<https://github.com/opensourcepos/opensourcepos/pull/3118#discussion_r586196636>:

>       /*
        Customers import from csv spreadsheet
        */
        public function csv()
        {
                $name = 'import_customers.csv';
-               $data = file_get_contents('../' . $name);
-               force_download($name, $data);
+               $allowed_tags = $this->Tag->get_definition_names(FALSE);


@objecttothis<https://github.com/objecttothis> are you fine to make it person_attributes as @daN4cat<https://github.com/daN4cat> ? Let's make sure we're on the same page here then.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/opensourcepos/opensourcepos/pull/3118#discussion_r586196636>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEI2X243ZFU2UKM3T7FJQ3TTBXVBDANCNFSM4YJ3XYLQ>.

2021-03-03 19:51 UTC, daN4cat commented on application/controllers/Customers.php
> +		$allowed_tags = $this->Tag->get_definition_names(FALSE);
Yeah, I'm concerned about tags being a semantic set / grouping concept.

2021-03-04 08:32 UTC, jekkos commented on application/controllers/Customers.php
> +		$allowed_tags = $this->Tag->get_definition_names(FALSE);
Ok person_attributes it is.

2021-03-04 14:21 UTC, DamianoSilverhand commented on application/controllers/Customers.php
> +		$allowed_tags = $this->Tag->get_definition_names(FALSE);
Will start working on the recommended changes, meaning I will have to create a new branch `person_attributes` for my next PR

2021-03-05 06:50 UTC, objecttothis commented on application/controllers/Customers.php
> +		$allowed_tags = $this->Tag->get_definition_names(FALSE);
> 
> 
> @objecttothis are you fine to make it person_attributes as @daN4cat ? Let's make sure we're on the same page here then.

No complaint here.  Sorry for not being able to respond earlier.

2021-03-05 06:54 UTC, objecttothis commented on application/controllers/Customers.php
> +							'phone_number'	=> $line['Phone Number'],
Yes, in fact it's better to refactor the rest so all of them are using the key names.  This provides a few advantages.

1. If the user moves columns around in their CSV it will still process them properly (as long as they don't change the names of columns.
2. It's easier to read in the code.

2021-03-05 06:58 UTC, objecttothis commented on application/controllers/Customers.php
> +					$consent = $line['Consent'] == '' ? 0 : 1;
This functionality wasn't in there before so if you don't want to include it then that's fine, but you might take a look at how I've handled true/false/0/1/NULL columns in item imports from #3029.  I'm not sure, but current implementation here won't be able to handle true/false/TRUE/FALSE/NULL, but instead translating them all to 1.

2021-03-05 07:05 UTC, objecttothis commented on application/controllers/Customers.php
>  	public function csv_import()
with #3029 I have a function in the importfile_helper called get_csv_file().  You'll want to use that here to take advantage of code_reuse, and that I've done extensive speed optimizations on that function to reduce time it takes to injest large files.  It's not as good of a system as an injest queue would be, but we don't currently have that in the code.

2021-04-16 07:15 UTC, DamianoSilverhand commented
@jekkos @objecttothis  @daN4cat  I am kindly requesting that this PR be closed in favor of #3161 , branch person attributes, with reworked changes and additions and extension of person attributes to Suppliers and Employees.

2021-04-16 07:16 UTC, closed without merging