Text improvements
opensourcepos/opensourcepos pull request #3306
Opened 2021-09-17 17:39 UTC by BudsieBuds

Split from #3278 and updated for this PR.

Here's an attempt at updating, cleaning up, and better document some of the non-trivial files. I'll try my best to explain the decisions I made below.

1. Tried to go for a better-looking `README.md`. Changed some text around and more. The emojis are up for debate, but they probably make everything easier to find and read.

2. Revamped the `WHATS_NEW.txt` file into a `CHANGELOG.md` file. The file is made interactive, typos were fixed, and consistency is improved. I would suggest updating the new file when committing something notable to master, for team and user reference. Another suggestion would be to split changes up into categories, f.e. Added, Changed, Fixed, Removed, Security, Deprecated, etc.

3. The same treatment was applied to the `INSTALL.md` and `UPGRADE.txt` (now `.md`).

4. Changed the `LICENSE` file to a fresh copy of the MIT license from https://choosealicense.com and added the additional bit at the end. It's an attempt to have GitHub detect the license and project it on the repo's page. Also removed the additional bit for older versions. It's still included with older releases and obviously not applicable on newer versions.

5. Updated the `.gitignore` file to be more descriptive and added some common to be ignored files.\
   Removed `package-lock.json` as it's intended to be committed [as mentioned here](https://docs.npmjs.com/configuring-npm/package-lock-json) and `npm_modules` as that doesn't seem to be used.\
   You could have a look if something else can be removed from the file, just to keep it clean. Especially in the `# Other` section, the rest seems to be accounted for.

6. Moved the `FUNDING.yml` file to the `.github` directory [as recommended here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository).

7. Added `package.md` and `composer.md` to explain their `.json` counterparts by describing what's the purpose of a dependency and what scripts are available to run. Skipped the Bower file because this will probably be phased out in the near future.

8. Changed the new `SECURITY.md` to the right supported application version. Also added the email address as the hyperlink title for easier access.

9. Replaced the deprecated `MAINTAINER` in `Dockerfile`. Could someone who knows more about this file [paste it in hadolint](https://hadolint.github.io/hadolint/) and solve the issues that pop up?

10. Small changes to `package.json` that shouldn't affect anything. F.e. updated `npm` to the newest `6.x.x` version, updated `bootstrap` and `bootswatch` to `^5.1.1`. Running npm seems broken at the moment because the Grunt plugins aren't compatible with the `grunt` version.

11. Small text correction in `bower.json`, `composer.json`, and `package.json` files.

Please read over everything, especially since English is not my native language.

With updating and cleaning up in mind, there's some things that popped up in my head. Here's some spitballing that should probably be in seperate issues. If there are bullet points that you want to explore and discuss, I'll make an issue for that. But I'd like to throw 'm against the wall and see what sticks.
- Upload [the emblem logo](https://github.com/opensourcepos/opensourcepos/blob/master/branding/emblem.svg) to the organization.
- Can unused branches be deleted?
- The [release 3.3.5](https://github.com/opensourcepos/opensourcepos/releases/tag/3.3.5) has the wrong changelog.
- Can the translation updates be moved to a different branch? This'll save some build minutes and the diff between versions will be smaller and more readable. This reduces the translations to a single commit before a release.
- You might want to think about adding more funding options. Donations should be as accessible and easy as possible. Different people prefer different ways of donating.
- I'd like to have another way to get in touch with the team. I've looked into it and did some testing. MS Teams (free) came out as the best option for multiple reasons. Let me know if you're interested and I'll set it up. Goes without saying, but every update and such should still be posted on GH. It's just for smaller questions, show some WIP and whatever. These bullet points would be stuff I would've thrown in there to see what needs more discussion here on GH.

Ready for the feedback. Cheers!

2021-09-18 20:56 UTC, jekkos commented
Hi @BudsieBuds , thanks for this clean changeset!

I can upload the emblem, good idea.
Yes you can delete branches that were merged previously, i try to do that most of the time. So now and then i go over the repo and then prune any stale branches.
I think indeed a staging branch can be configured for weblate. On the other hand i do like the idea that people can submit translations and have a build with those updates right after. Downside is indeed more commits with not a lot of semantics. Not sure if anyone hasa strong argument before or against?
I must admit that i also thought about funding to add eg crypto wallet addresses, but not sure if anyone would want to use those
I'll go through the changes a bit to see if there anything else.

2021-09-23 07:00 UTC, jekkos commented on CHANGELOG.md
> +## [3.3.5] - 2021-08-26
so this header now also has a link to a diff on github? nice

2021-09-23 07:00 UTC, jekkos commented on Dockerfile
> +LABEL maintainer="jekkos"
can be removed if it's deprecated

2021-09-23 07:01 UTC, jekkos commented on Gruntfile.js
> -						cwd: 'node_modules/bootstrap-5',
can we remove the suffix here?

2021-09-23 07:01 UTC, jekkos commented on LICENSE
> +Copyright (c) 2021 BudsieBuds
Deserved

2021-09-23 07:02 UTC, jekkos commented on SECURITY.md
> +| 7.3       | 3.3.5                                              |
In fact this fix was reverted, I need to reinstate it before the next release, or fix this file

2021-09-23 07:03 UTC, jekkos commented on UPGRADE.md
> +
Thanks for the reormat, looks good

2021-09-23 07:04 UTC, jekkos commented on package.json
> +    "bootstrap": "^5.1.1",
Not sure what happens if you remove the npm version.. I had some issues with later versions last time if I remember well

2021-09-23 07:05 UTC, jekkos commented on composer.md
> +# composer.json
is this standard practice in php projects to document the used dependencies? Doesn't composer.json allow you to do sth similar or do we need separate files?

2021-09-28 07:36 UTC, jekkos commented on SECURITY.md
> +| 7.3       | 3.3.5                                              |
We'll need to bump this to 3.3.6, I have reinstated the fix.

2021-09-28 07:37 UTC, jekkos requested changes
Some comments need to be worked out first

2021-10-05 20:12 UTC, daN4cat commented
I've resolved the conflicts with latest master.

2021-10-06 19:43 UTC, BudsieBuds commented
@jekkos @daN4cat Yeah, sorry for going AWOL. I posted this PR just before leaving on a trip. I've added preview links to my original post for the Markdown files and I'll get to reviewing the requested parts.

2021-10-06 19:44 UTC, BudsieBuds commented on Dockerfile
> +LABEL maintainer="jekkos"
It has been removed.

2021-10-06 19:44 UTC, BudsieBuds commented on Gruntfile.js
> -						cwd: 'node_modules/bootstrap-5',
Yeah, the suffix should be removed.

2021-10-06 19:44 UTC, BudsieBuds commented on SECURITY.md
> +| 7.3       | 3.3.5                                              |
Has been bumped.

2021-10-06 19:48 UTC, BudsieBuds commented on composer.md
> +# composer.json
I don't think it's standard practice, I just like everything documented mainly because multiple people can help improve the code and documentation should make that easier. Also for reviewing if packages are still being used from time to time. Unfortunately, as far as I know, the JSON format doesn't allow for comments to be added. I'll let you guys decide if this is something that's worth the effort.

2021-10-07 11:22 UTC, jekkos commented on composer.md
> +# composer.json
I think i like the idea but maybe we should add it in the INSTALL or another file? We might end up with too many files otherwise?

2021-10-07 11:23 UTC, jekkos commented on package.json
> +    "bootstrap": "^5.1.1",
Try to rebuild and check if all works fine in case you want this removed.

2021-10-07 12:58 UTC, BudsieBuds commented on package.json
> +    "bootstrap": "^5.1.1",
The `npm:bootstrap/watch` prefix was only needed when we downloaded two versions of Bootstrap and Bootswatch through npm.

2021-10-07 12:59 UTC, BudsieBuds commented on CHANGELOG.md
> +## [3.3.5] - 2021-08-26
Yeah, check out the [preview here](https://github.com/opensourcepos/opensourcepos/blob/c72afff00a54b67f2b673acbb40e92c80fceb50b/CHANGELOG.md).

2021-10-07 13:00 UTC, BudsieBuds commented on composer.md
> +# composer.json
Fine by me, or maybe just keep the `package.md` and move all dependency info to that file?

2021-10-08 20:26 UTC, jekkos commented on CHANGELOG.md
> +## [3.3.5] - 2021-08-26
Look really great, thanks!

2021-10-08 20:39 UTC, jekkos commented on README.md
> +<a href="https://travis-ci.org/opensourcepos/opensourcepos" target="_blank"><img src="https://travis-ci.com/opensourcepos/opensourcepos.svg?branch=master" alt="Build Status"></a>
the file extension is markdown but this is html?

2021-10-08 20:42 UTC, jekkos commented on README.md
> +| <div align="center"><img src="https://upload.wikimedia.org/wikipedia/commons/9/9c/IntelliJ_IDEA_Icon.svg" alt="IntelliJ IDEA Logo" height="50"></div> | <div align="center"><img src="https://secreth
same here, mixed up html/markdown

2021-10-08 20:43 UTC, jekkos commented on composer.md
> +# composer.json
Yes let's maybe have a file that summarizes this a bit

2021-10-08 20:49 UTC, jekkos commented
@BudsieBuds regarding the weblate updates, I think they will be separate commits as each file is a weblate 'component' and thus managed separately. It does seem that there is an addon in weblate that can [squash commits from one author](https://github.com/WeblateOrg/weblate/pull/2462). I might want to take a look at this and then try to upgrade weblate once I get to it.

2021-10-08 21:22 UTC, BudsieBuds commented on README.md
> +| <div align="center"><img src="https://upload.wikimedia.org/wikipedia/commons/9/9c/IntelliJ_IDEA_Icon.svg" alt="IntelliJ IDEA Logo" height="50"></div> | <div align="center"><img src="https://secreth
Same reason as above.

2021-10-08 21:52 UTC, BudsieBuds commented
> Doing a call is fine by me. I'm not sure if there any free OSS alternatives for teams as it doesn't work very well on GNU/Linux. As an alternative we could try and test this one? https://tox.chat/download.html

Calls can be done for sure, but that's not the only reason I'd like a way to contact everyone. For questions, generally easier contact, and maybe a bit of chatter. I've looked at Mattermost, but that has to be hosted. Then there's Slack, Element, and Discord. I'm not familiar with Tox.

My considerations among others; system availability, GitHub integration, and pricing. Teams is available on a lot of platforms, has GitHub integration, and a generous free tier. However, I only have experience with this software on Windows and Android. Mattermost looks really interesting, but has to be hosted and maintained.

> I have uploaded the emblem also, one minor issue was that GH does not accept SVG so had to convert it to JPEG. It might be not all that nice as it has lost the transparancy on the edges.

[Here](https://user-images.githubusercontent.com/12870258/136628458-d9dfada7-cd87-4df4-ab9f-1c185ca153dd.png) you go. That'll probably look best.

2021-10-14 21:10 UTC, jekkos commented on package.json
> +    "bootstrap": "^5.1.1",
@BudsieBuds can we resolve this one?

2021-10-20 14:35 UTC, BudsieBuds commented on composer.md
> +# composer.json
Combined into DEVELOPMENT.md. Needs improvements in the future, good enough for now.

2021-10-20 19:17 UTC, jekkos commented
@BudsieBuds I'd like to check first if the build here actually works.. I'll recreate the branch in the organization's repo. My guess is that the phpunit bump will break the unit tests.

2021-10-20 19:24 UTC, BudsieBuds commented
@jekkos Wait, I didn't bump the phpunit version right?

2021-10-20 20:34 UTC, closed without merging

2021-10-20 20:34 UTC, jekkos commented
The README.md looks neat now! Thanks!