Keyboard Shortcuts/Hotkeys
opensourcepos/opensourcepos pull request #3312
Opened 2021-09-23 20:18 UTC by WebShells

Added Shortcuts/Hotkeys to Register

ESC 	Cancels Current Quote/Invoice/Sale
ALT + 1 	Item Search
ALT + 2 	Customer Search
ALT + 3 	Suspend Current Sale
ALT + 4 	Show Suspended Sales
ALT + 5 	Edit Amount Tendered
ALT + 6 	Add Payment
ALT + 7 	Add Payment and Complete Invoice/Sale
ALT + 8 	Finish Quote/Invoice witdout payment
ALT + 9 	Open Shortcuts Window

#1964 #2673 #1630 #2618 #2554 #1083 #425

2021-09-24 04:47 UTC, objecttothis requested changes
Great work on this!  Just the few comments.

2021-09-24 04:47 UTC, objecttothis commented on application/views/sales/register.php
> +
Whitespace was added into the code here

2021-09-24 04:47 UTC, objecttothis commented on application/views/sales/register.php
> +
and here

2021-09-24 04:47 UTC, objecttothis commented on application/views/sales/register.php
> +
extra whitespace

2021-09-24 04:47 UTC, objecttothis commented on application/views/sales/register.php
> +					<button class='btn btn-default btn-sm modal-dlg' id='show_keyboard_help' data-href="<?php echo site_url($controller_name."/sales_keyboard_help"); ?>"
Don't use " in php when no string interpolation is happening because it calls the parser unnecessarily.  This php should either be:
`<?php echo site_url($controller_name.'/sales_keyboard_help'); ?>`

or even better, use string interpolation

`<?php echo site_url("$controller_name/sales_keyboard_help"); ?>`

2021-09-24 04:47 UTC, objecttothis commented on application/views/sales/register.php
> +		case 27: // ESC Cancel Current Sale
This could be problematic without some kind of a confirmation dialog "Are you sure you want to cancel this sale?"  I don't feel super strongly about it, but I can see one of our staff accidentally hitting escape and losing the entire sale.

2021-09-24 04:47 UTC, objecttothis commented on application/language/ar-EG/sales_lang.php
> +$lang["sales_key_help"] = "Shortcuts";
In the future you can save yourself some time by just adding these to the default language, which is English (US) and Weblate will pick it up for you.

2021-09-24 04:48 UTC, objecttothis commented
@WebShells I didn't have time to test the feature.  Maybe @odiea could give it a spin?

2021-09-24 10:45 UTC, odiea commented
Great addition. Looks and works good

2021-09-24 13:44 UTC, WebShells commented on application/views/sales/register.php
> +		case 27: // ESC Cancel Current Sale
@objecttothis while trying it the browser sent back a confirmation dialog upon pressing ESC. I can easily add it if there is a need for it no problem.

2021-09-24 13:50 UTC, WebShells commented
> 
> 
> Great addition. Looks and works good

> 
> 
> Great work on this! Just the few comments.

Thanks for the review guys comments were resolved. 
I think it will help during the sales process if the employee got used to these shortcuts.
Do you think we should add them to db and make them configurable/re-arrange-able or this is enough ?

2021-09-29 10:12 UTC, jekkos commented on application/views/sales/register.php
> +			$("#item").focus();
@WebShells might be nitpicking but I think you can chain these operations so that they are on one line.

2021-09-29 10:17 UTC, jekkos commented on application/views/sales/register.php
> +			$("#show_suspended_sales_button").click();
As you suggest I think we could make this functionality quite a bit better by loading an associative array from database that contains keycode as key and field id as value? It will make this code a bit more generic as you need to determine the object type you find (focus and select in case of a dropdown, click in case of a button)

2021-09-29 10:17 UTC, jekkos commented on application/views/sales/help.php
> +					<td><code>F11</code></td>
great idea to have this help page here!

2021-09-29 10:17 UTC, jekkos commented on application/language/zh-Hant/sales_lang.php
> +$lang["sales_key_help"] = "Shortcuts";
might be nitpicking but we might just leave new keys empty now. It's more clear in weblate that the string needs a translation in that case. So better for statistics.

There is a fallback in place that loads english translations for empty strings.

2021-09-29 10:24 UTC, jekkos commented on application/views/sales/register.php
> +			$("#show_suspended_sales_button").click();
So in that case this logic will be encoded in a datastructure instead. I think configuring this from the UI might be out of scope for this PR. But then people will be able to change mappings by running a database query?

2021-09-29 13:45 UTC, jekkos commented
If you merge master in this branch, we might see the commit twice in the end

2021-09-29 14:18 UTC, objecttothis approved these changes

2021-09-29 14:19 UTC, objecttothis commented
Sorry, I think it's kinda dumb that when one person requests changes another can't approve the changes and the person merge... The original person has to go back in and approve it.  I wish they made it an option to merge if at least one approval happens regardless of who requested changes.

2021-10-01 06:33 UTC, jekkos commented
> Sorry, I think it's kinda dumb that when one person requests changes another can't approve the changes and the person merge... The original person has to go back in and approve it. I wish they made it an option to merge if at least one approval happens regardless of who requested changes.

But then we would just bypass that commenter's concern no?

2021-10-01 09:20 UTC, objecttothis commented
> > Sorry, I think it's kinda dumb that when one person requests changes another can't approve the changes and the person merge... The original person has to go back in and approve it. I wish they made it an option to merge if at least one approval happens regardless of who requested changes.
> 
> But then we would just bypass that commenter's concern no?

I meant only that only another approved "approver" could override rather than just anyone.

2021-10-05 20:19 UTC, daN4cat commented
Is this good to merge in? (Provided the merge conflict is solved....)

2021-10-13 11:33 UTC, jekkos commented
@WebShells I have tried the branch but the shortcuts don't work for me in Firefox. It seems that ALT combinations are already shortcuts within FF itself, so it's not usable.

I'm quite certain that it will only add value once you allow a user to override the bindings. I haven't tested in chrome but maybe someone else can confirm whether this works?

2021-10-15 22:36 UTC, WebShells commented
@odiea holaaa thanks for testing it

2021-10-16 08:41 UTC, jekkos commented
@WebShells It might be gnome on linux that has overlapping shortcuts, using alt+number just brings up the n-th tab in my FF?

2021-10-16 08:42 UTC, jekkos commented
@opensourcepos/org to merge or not to merge?

2021-10-16 10:58 UTC, WebShells commented
My vote is to merge. 
I'll be following it with an update to re-assign keys based on users interest and displaying it on keyboard shortcuts help page for 3.3.7, but i don't want/prefer to postpone this one to future releases.

2021-10-19 21:00 UTC, merged

2021-10-21 07:34 UTC, jekkos commented
@WebShells I was thinking that the help button might not be in the best place currently. It also disappears once you add an item to the register. Maybe something we can get some advice on from @BudsieBuds as he seems to be quite UX savvy.