Ci4 upgrade
opensourcepos/opensourcepos pull request #3592
Opened 2022-11-13 22:14 UTC by jekkos

@objecttothis I'll make a new PR here already

2022-11-17 07:48 UTC, objecttothis commented
I've created a draft PR just to compare the two branches.  We are going to need to write a special upgrade instructions document for this upgrade.  @odiea do you care to do this?  It will need to include things like manually moving images in item_pics, etc to the new location...

2022-11-17 07:52 UTC, objecttothis commented
Does this new CI4 branch include the changes from the master that were merged since the original codeigniter_4_upgrade branch was created?  Those are going to manually need to be ported to the CI4 format. If they are blindly merged in then they won't work because the syntax for many things is different.

2022-11-17 11:30 UTC, objecttothis commented
@jekkos did we decide whether this version will be 3.4.0 or 4.0.0

2022-11-17 22:42 UTC, jekkos commented
@objecttothis I always thought to stick to 3.4.0, as we do no really add new features. But this might not be reflecting the fact that the upgrade was a huge effort.

2022-11-17 23:28 UTC, jekkos commented on app/Config/migration.php
>  /*
this file might be a leftover

2022-11-18 06:08 UTC, objecttothis commented
> @objecttothis I always thought to stick with 3.4.0, as we do not really add new features. But this might not be reflecting the fact that the upgrade was a huge effort.

That's fine.  I'll push a commit.

2023-01-27 08:32 UTC, objecttothis commented
@opensourcepos/org Yesterday I finished upgrading the base code from CI 4.2.10 to 4.3.1. Today I will be walking through https://codeigniter.com/user_guide/installation/upgrading.html starting with 4.0.x to 4.0.4 and moving up. If anyone plans to work on this branch, let's coordinate in the devroom channel on gitter.

@jekkos I needed to rename the Error language file to Errors and add a few phrases.  I've done so in the en-US language.  I would be surprised if weblate automatically picks this up.  Are you able to sort it out sometime?

2023-02-05 12:16 UTC, objecttothis commented
@opensourcepos/org Migrations now converts existing CI3 migrations tables to CI4 style and populates the table with all the rows up to and including the last migration successfully run.  This will ensure that migrations don't get re-run. If it's a clean install, then the CI4 table gets created and all migrations run from the beginning.

2023-02-05 13:21 UTC, jekkos commented
> @opensourcepos/org Migrations now converts existing CI3 migrations tables to CI4 style and populates the table with all the rows up to and including the last migration successfully run. This will ensure that migrations don't get re-run. If it's a clean install, then the CI4 table gets created and all migrations run from the beginning.

Great news so then the issue is solved? Meaning we don't need to look into removing migrations that were already ran

2023-02-05 13:24 UTC, objecttothis commented
> > @opensourcepos/org Migrations now converts existing CI3 migrations tables to CI4 style and populates the table with all the rows up to and including the last migration successfully run. This will ensure that migrations don't get re-run. If it's a clean install, then the CI4 table gets created and all migrations run from the beginning.
> 
> Great news so then the issue is solved? Meaning we don't need to look into removing migrations that were already ran

Correct. I decided instead to get the current version, then loop through all the migrations and add each row until it got to a version that hadn't been run.  No need to delete files programmatically.

2023-02-08 20:55 UTC, objecttothis commented
@opensourcepos/org I feel like a giddy schoolgirl! I finally figured out how to make the user_info and allowed_modules data generated in the secure controller available to the partial/header view!  The CSS is still jacked and there are still lots of kinks to work through.
![image](https://user-images.githubusercontent.com/17935339/217647014-8cea1b63-56fc-41c6-9553-ddbb7b62324d.png)

My next steps are to work through each of the main views and fix the bugs causing exceptions.  @jekkos will you be able to sort out the weblate stuff any time soon? @SteveIreland I promise to not touch the dependency files again or you might just beat me like a drum. @odiea As the functionality improves, I believe you want to poke around. In short, we need an issue for each bug that we find.  I don't know if it allows you to do this, but if you are able to edit the first post in this PR when you create a new issue to add the issue number and that it needs an owner, that would be helpful.  Also, I recommend CI4 related issues be either prefaced with `CI4:` or we should make a category called CI4 so that we can easily find those tickets.

I haven't made an issue for this yet, but we are going to need to update the documentation to include a step-by-step install from Docker, a release build and manual build.  I think there will be changes to all three.  Also, each step should probably include instructions for clean install and for upgrade from 3.0.2+ to 3.4.0.

@daN4cat are you still around these days? I'm just curious what your status with OSPOS is at this point?

2023-02-08 21:47 UTC, objecttothis commented
OK, last commit for the night. I'm taking Thursday and Friday off.  I will be back at it on Monday.  Feel free to have at it. If someone wants to take a particular Controller to work on, or some other part, just message the group so we know you're working on it.

![image](https://user-images.githubusercontent.com/17935339/217658306-1a128056-99c5-4850-befc-3d581e752580.png)

2023-02-17 23:35 UTC, jekkos commented on app/Config/OSPOS.php
> +	public string $commit_sha1 = 'dev';	//TODO: Travis scripts need to be updated to replace this with the commit hash on build
we'll need to run the find/replace on this file now

2023-02-18 10:46 UTC, objecttothis commented on app/Config/OSPOS.php
> +	public string $commit_sha1 = 'dev';	//TODO: Travis scripts need to be updated to replace this with the commit hash on build
Yeah, if we leave it as 'dev' in the master, it should be easy enough to do a find/replace and substitute the commit sha1.

2023-02-18 21:59 UTC, jekkos commented on app/Database/tables.sql
> +	('language_code', 'en-US');
wasn't this updated in a migration at some point?

2023-02-18 22:17 UTC, objecttothis commented on app/Database/tables.sql
> +	('language_code', 'en-US');
Probably, but that's moot because for new installs that just have a clean database from database.sql and haven't run any of the migrations, not changing this here breaks the language output until you run the migrations the first time.

2023-02-20 08:09 UTC, jekkos commented on app/Database/tables.sql
> +	('language_code', 'en-US');
Ah I thought we would stick to the same approach as before, so that means go through all migrations even if we're doing a clean install? This way we know the process works?
Changing it this way means we'll break the functionality in the version the migrations initially start from.

As an alternative we could from the build generate a full dump from a clean initialized database that has all migrations executed, to make sure that this state is consistent with the outcome of running all migrations one by one.

2023-02-20 19:48 UTC, objecttothis commented on app/Database/tables.sql
> +	('language_code', 'en-US');
> Ah I thought we would stick to the same approach as before, so that means go through all migrations even if we're doing a clean install? This way we know the process works? Changing it this way means we'll break the functionality in the version the migrations initially start from.
> 
> As an alternative we could from the build generate a full dump from a clean initialized database that has all migrations executed, to make sure that this state is consistent with the outcome of running all migrations one by one.

If we go the route of making it a migration with tables.sql set as `('language_code', 'en');` then none of the lang() calls will work when the first login is done. It looks like this:
![image](https://user-images.githubusercontent.com/17935339/220186008-f79e4c2a-fa2f-4b25-9b79-d15ca72d1732.png)

This is because switching from en to en-US meant removing the en folder entirely in \App\Languages\ therefore it's a breaking change. Once the migrations runs 3.0.2_to_3.1.1.sql then it will work.

The other approach you suggested of generating database.sql so that it includes the complete table structure up to the most recent migration, would resolve the problem, but it seems like a lot of work to me.

I think the change I'm proposing is actually a change in doctrine about tables.sql and constraints.sql.  That change would be as follows: tables.sql and constraints.sql must be frozen at 3.0.2 unless the change is a breaking change for new installs. As far as I know, the only time it would be a breaking change is if it affects the login, since the migration happens immediately upon first login.  Another example of what would constitute a breaking change is if for some reason we were storing the full path of the company logo in the database (I know we aren't, but humor me). If the Login controller checked the database to send the full path on to the view, and tables.sql had the default full path be \application\foobar.jpg, but in CI4 it's physically now \app\foobar.jpg that would be a breaking change for new installs.

Alternately we could have the migration run automatically before the Login view is loaded, but I suppose that could be problematic. At least there would not be any breaking changes and we could be more hardcore about keeping tables.sql and constraints.sql frozen.

2023-02-20 20:46 UTC, jekkos commented on app/Database/tables.sql
> +	('language_code', 'en-US');
Ok now I understand the rationale, if we can only run migrations after login, then agree this might be the best way. But beside that I'd like to touch it as little as possible and encode any subsequent changes into a migration.
It's indeed better to only run migration on login. Otherwise some unwanted side effects can occur. Thanks for all the work your doing here btw, I find myself quite overloaded by work these days and so not always up to coding anything extra after 8-10h behind a screen already.

2023-02-20 21:01 UTC, objecttothis commented on app/Database/tables.sql
> +	('language_code', 'en-US');
> Ok now I understand the rationale, if we can only run migrations after login, then agree this might be the best way. But beside that I'd like to touch it as little as possible and encode any subsequent changes into a migration. It's indeed better to only run migration on login. Otherwise some unwanted side effects can occur. 

Agreed that we should touch tables.sql and constraints.sql as little as possible.

> Thanks for all the work your doing here btw, I find myself quite overloaded by work these days and so not always up to coding anything extra after 8-10h behind a screen already.

No problem.  I completely understand about not having the capacity after being in front of a screen all day. In the next 3-4 weeks I'm likely going to slow down a little because I have to oversee a remodel on the bookstore we run.

2023-02-28 16:46 UTC, objecttothis commented
@opensourcepos/org if anyone is going to be contributing to this PR and wants help getting caught up to speed on CI4 or setting up debug in their IDE please let me know and I'll be glad to help.  I've had to do a lot of getting to know CI4 through this project so if it can save people time to explain something so that the project goes quicker, then it's worth it.

2023-03-03 13:58 UTC, objecttothis commented on app/Models/Employee.php
> +	public function logout()
@SteveIreland thank you for fixing this.  We need to have a return type on each function except where there are multiple potential return types.  This is to prevent strange bugs introduced by returning one type of value when its expecting another and PHP dynamic typing the return value into something we aren't expecting.  In this case not a big deal, but for consistency we need to add void as the return type.  `public function logout(): void`

2023-03-03 14:10 UTC, SteveIreland commented on app/Models/Employee.php
> +	public function logout()
Understood.  It's a good practice.

2023-03-03 14:35 UTC, objecttothis commented on app/Controllers/Home.php
> +	public function getLogout(): \CodeIgniter\HTTP\RedirectResponse
@SteveIreland this should be replaced with an import.  So below the namespace reference place `use CodeIgniter\HTTP\RedirectResponse;` and this function signature becomes `public function getLogout(): RedirectResponse`

2023-03-17 01:41 UTC, odiea commented
@SteveIreland  While your changing stuff you might consider getting rid of , 'attr' because the form fields look like this. Employees&#x20;Wages

2023-03-19 12:19 UTC, odiea commented
In forms with a check box it is always checked. Any Ideas?

2023-03-19 22:57 UTC, objecttothis commented
> @objecttothis . This is from the getView in Suppliers controller. foreach(get_object_vars($info) as $property => $value) 94 { 95 $info->$property = $value; 96 } 97 $data['person_info'] = $info; 98 $data['categories'] = $this->supplier->get_categories(); 99 100 return view("/suppliers/form", $data);

getView() must be marked as `: void` and on line 100 we have a return statement.  That needs to be resolved.  Either just calling view without the return or we need to change the return type on getView to match the return statement.  I'm still neck deep in remodeling so you can create an issue and add it to the list at the top of this PR and someone can pick it up, or I will when I get back.

2023-03-19 23:16 UTC, odiea commented
@objecttothis Sorry that was my error. I was testing return view instead of echo view and forgot it.

2023-04-02 23:43 UTC, odiea commented
Controller/expenses line 128 should be changed to void not vpid

2023-04-06 17:36 UTC, DEV-byoos commented
hello dev's

I installed the last commit opensourceospos upgrade ci4
some modifications are needed:
PROPOSALS:
 IN /root/app/Views/Login.php
FIX <link href="<?="dist/**bootswatch-5**/$theme/bootstrap.min.css" ?>" rel="stylesheet" type="text/css">
	TO
	<link rel="stylesheet" type="text/css" href="<?php echo 'dist/bootswatch/' . (empty($config['theme']) ? 'flatly' : esc($config['theme'])) . '/bootstrap@3.4.1/bootstrap.min.css' ?>"/>
i am move to /bootstrap@3.4.1/bootstrap.min.css and testing version bootstrap@5.3.0-alpha1.css it'ok

also for the header.php
AND IN /root/app/Views/partial/Header.php
	<link rel="stylesheet" type="text/css" href="<?php echo 'dist/bootswatch/' . (empty($config['theme']) ? 'flatly' : esc($config['theme'])) . '/bootstrap@5.3.0-alpha1/bootstrap.min.css' ?>"/>
AND added
	<link rel="stylesheet" type="text/css" href="dist/jquery-ui/jquery-ui.min.css"/>
	<link rel="stylesheet" type="text/css" href="dist/opensourcepos.min.css?rel=88e63d8098"/>


I'm stuck on internationalization
the template does not follow the local code, I'm working on it

config  CI4.3.3  and php8.2
I FIX  bugs as they arise

best regars
Gabriel

Translated with www.DeepL.com/Translator (free version)

2023-04-07 12:06 UTC, objecttothis commented on app/Controllers/Config.php
> +		$this->db = Database::connect();
I might be mistaken, but I don't think this is needed. Especially in a controller.

2023-04-07 12:09 UTC, objecttothis commented on app/Controllers/Config.php
> +			log_message('info', '>>> $mailchimp_api_key-' . $mailchimp_api_key);
If this was just needed for testing, we might want to remove it now that it's sorted.

2023-04-10 11:41 UTC, odiea commented
@SteveIreland  I get the following error when trying to create a new cashup.
CRITICAL - 2023-04-10 07:37:22 --> Call to undefined function App\Models\getEmptyObject()
in APPPATH\Models\Cashup.php on line 204.
 1 APPPATH\Controllers\Cashups.php(80): App\Models\Cashup->get_info(-1)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Cashups->getView()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cashups))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()

2023-04-11 12:29 UTC, SteveIreland commented on app/Controllers/Config.php
> +		$this->db = Database::connect();
I try hard not to add anything that's not needed.  But it was complaining it was missing, so I added it.

But seriously, there should be a better way of doing it and I'm open to CI4/PHP wizards showing me the true path.

2023-04-11 12:54 UTC, odiea commented
@SteveIreland . I tried that earlier but the new form shows as follows.

![2023-04-11 06_52_23-Window](https://user-images.githubusercontent.com/10962177/231168380-27baf3f6-6d7e-41e9-89a7-b7ad684fdcd7.png)

2023-04-12 17:43 UTC, objecttothis commented on app/Controllers/Config.php
> +		$this->db = Database::connect();
I hear you @SteveIreland . I just had a chance to pull in all the changes and take a look. Thanks for all your work on this BTW.  It's quite the godsend, since I wasn't going to be able to work on it while doing this remodel.  It appears that the reason that it's complaining about it not being there is because `$this->db->transStart();` and `$this->db->transComplete();` are peppered throughout the code.  Curiously, I was the one that added the transactional statements!  That said, let's keep this in, but I think in a later feature change (i.e., different PR) we should move the transaction statements to the model and then use thrown exceptions to be aware of problems rather than calling `$this->db->transStatus()` in the Controller to see if it was successful.

2023-04-16 12:21 UTC, odiea commented
With the following new code added in cashup model and after you added extra in config forms the css is not correct.
```
if(!$count_only)
		{
			$builder->select('
			cash_up.cashup_id,
			');
		}
		else
		{
```
I get the following error.

CRITICAL - 2023-04-16 08:13:13 --> Undefined property: stdClass::$open_date
in APPPATH\Helpers\tabular_helper.php on line 883.
 1 APPPATH\Helpers\tabular_helper.php(883): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: stdClass::$open_date', 'APPPATH\\Helpers\\tabular_helper.php', 883, [...])
 2 APPPATH\Controllers\Cashups.php(59): get_cash_up_data_row(Object(stdClass))
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Cashups->getSearch()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cashups))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()

2023-04-21 12:02 UTC, odiea commented
good job. Register now works . I could also save an Invoice by deleting payment_message in views invoice.php. This appears in quotes also.

2023-04-21 12:08 UTC, odiea commented
Once you figure this issue out we should be able to reprint a Receipt. Thanks for all the work you are doing.
CRITICAL - 2023-04-21 07:57:14 --> Undefined property: app\Libraries\Sale_lib::$sale
in APPPATH\Libraries\Sale_lib.php on line 1149.
 1 APPPATH\Libraries\Sale_lib.php(1149): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: app\\Libraries\\Sale_lib::$sale', 'APPPATH\\Libraries\\Sale_lib.php', 1149, [...])
 2 APPPATH\Controllers\Sales.php(1626): app\Libraries\Sale_lib->copy_entire_sale(2811)
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Sales->postUnsuspend()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sales))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()

2023-04-28 11:38 UTC, odiea commented
@SteveIreland . It appears that you have not had time to find the following issue. In tabular_helper I think that the line numbers are 96 and 97 needs to be replace with the following for the Sales to show in the Manage view.

```
$controller = get_controller();
```

2023-05-01 20:27 UTC, odiea commented
I got Date and dropdown to show In items. I receive the following error after trying to save the info. Any Ideas on how to resolve this problem?

ERROR - 2023-05-01 16:24:44 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`ospos6`.`ospos_attribute_links`, CONSTRAINT `ospos_attribute_links_ibfk_2` FOREIGN KEY (`attribute_id`) REFERENCES `ospos_attribute_values` (`attribute_id`) ON DELETE CASCADE) in C:\wamp64\www\ireland\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\wamp64\www\ireland\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `os...', 0)
#1 C:\wamp64\www\ireland\vendor\codeigniter4\framework\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `os...')
#2 C:\wamp64\www\ireland\vendor\codeigniter4\framework\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `os...')
#3 C:\wamp64\www\ireland\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query('INSERT INTO `os...', Array, false)
#4 C:\wamp64\www\ireland\app\Models\Attribute.php(553): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\wamp64\www\ireland\app\Controllers\Items.php(745): App\Models\Attribute->save_link(63, 25, -1)
#6 C:\wamp64\www\ireland\vendor\codeigniter4\framework\system\CodeIgniter.php(934): App\Controllers\Items->postSave(63)
#7 C:\wamp64\www\ireland\vendor\codeigniter4\framework\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Items))
#8 C:\wamp64\www\ireland\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\ireland\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}

2023-05-17 00:04 UTC, odiea commented
@objecttothis @SteveIreland I was playing around with the Register this morning and included the buttons that were suggested for the earlier version. I will Upload the Register code if anyone is interested? It appears to be easier then using the old dropdown. The lower 3 buttons only show after a Customer is added to the Sale.

![2023-05-16 17_59_08-Window](https://github.com/opensourcepos/opensourcepos/assets/10962177/4bf7d7a0-215f-4511-8e82-f18c71a355d2)

2023-05-18 08:47 UTC, jekkos commented
Hi @odiea lets handle that in a separate PR against ci4.   It might be useful to make the payment methods configurable. This is a feature that is requested often and we just need to store the list as an array in the config store. This wat we dont overload the Ui and only show useful buttons to the heers.

2023-05-30 18:16 UTC, jekkos commented
These remaning conflicts are due to the translation files being edited in their old location. I'll try to move these changes to the new file structure in one go.

2023-06-11 11:51 UTC, jekkos commented on gulpfile.js
> +gulp.task('build-database', function() {
great indeed that should do it

2023-06-25 21:16 UTC, jekkos commented on .dockerignore
> +app/writable/session/*
This makes sense indeed, you're tesing the docker setup?

2023-06-26 02:37 UTC, SteveIreland commented on .dockerignore
> +app/writable/session/*
You caught me.  :-)   Yes.  I've spent most of this weekend learning Docker, Linux, and trying to make sense of all of the build scripts so that I can help out.  I can clean up the obvious stuff, but a lot of it still doesn't make sense or seems overly complicated - but, no doubt that is due to not knowing what I'm doing.   I was able to get the mariadb container running, but I was getting three script failures on the ospos container.  I just noticed that you made some changes, so I'll pull those and try again, and hopefully have better luck tomorrow.  Been reading the docker documentation to get a better grip on how things tie together.

2023-06-26 21:43 UTC, jekkos commented on .dockerignore
> +app/writable/session/*
cool great to hear, I thought I was almost done here but it seems something weird is going on with the travis build, I thought perhaps I'll temporarily build the base image (debian, php and apache) locally and push that, then add the CI code to it in the travis build. That will save us build credits but we"ll have to provide security updates ourselves. 

So I had it working at one point but was doing some minor tweaking but now the base install fails only on travis. Will give it a go for now and then we can switch back later.

2023-08-04 08:56 UTC, objecttothis commented
@opensourcepos/org I'm finally winding down my responsibilities with this remodel, so I'll be able to return to working on this again soon. @SteveIreland @jekkos or anyone else can you catch me up on what is left to be done?  Unfortunately the local government is requiring that I integrate OSPOS with their government cash registers. I had planned on tackling that after the CI4 changeover because it's dependent on events in CI4, but now I need to implement it in our current production build and then port it over to OSPOS and this repo later after the CI4 implementation is in production.  That said, I won't be able to fully jump back into this PR until I've got something working.

2023-08-05 10:33 UTC, jekkos commented
Thanks for the update @objecttothis . What version do you have then currently in production? Is it already based on CI4? I would be very happy to land this effort and some focus will be required, so I'll try to free up some time to do it.

2023-08-05 11:45 UTC, objecttothis commented
> Thanks for the update @objecttothis . What version do you have then currently in production? Is it already based on CI4? I would be very happy to land this effort and some focus will be required, so I'll try to free up some time to do it.

In production I am running 3.3.2 which is CI 3.1.13-based.  I had some code not in the repo for 3rd party API calls and I am waiting to upgrade production until we have 3.4.0 AND a solid 3rd party integration structure (see #3789) so that I can port the code over to a version of OSPOS based on CI4.

That said, in dev I had the current build of this branch that I was coding against and testing before I had to break for the remodel work at the bookstore.  Since then I think you and @SteveIreland worked on changes to the build process, so I'll need to get my dev environment up to speed and re-learn the build process.  

I'm glad you are looking at freeing up some time.  Next week I am going to be camping and then traveling a little the following week.  When I return my order of priority is as follows:

1. Hack together the API integration with the local government cash register on my current production build.
2. Help finish this PR.
3. Work on and finish #3789 
4. Work on and finish #3790
5. Port the two 3rd party API integrations that my business uses to this repo.

After that I'll re-evaluate what to work on, but I'll likely be returning to just working on this project 3 days per week at that point.

2023-08-30 19:06 UTC, jekkos commented
I'm thinking on how we should proceed with the current state of this branch, we have some conflicts with master that are not easy to resolve without creating a mess in the git history. I also saw that we have some duplicated history due to merges that were done in local development branches, which makes the rebase process even more painful.

I thought to create a diff between current branch and master and apply it as one commit again on top of it. But at least I want the author to be retained on the code lines, so it might not be ideal. Another option would be squashing subsequent commits per author and then rebase that result. This will at least retain the author info, and reduce the noise a bit at certain points in time. 
If we would have worked through PRs I suppose history would have looked more or less like this. Most features or commits are squashed into one and then put on top of master.
Any opinions on this?

2023-09-01 11:06 UTC, objecttothis commented
> I'm thinking on how we should proceed with the current state of this branch, we have some conflicts with master that are not easy to resolve without creating a mess in the git history. I also saw that we have some duplicated history due to merges that were done in local development branches, which makes the rebase process even more painful.
> 
> At least I want the author to be retained on the code lines. A solution would be to squash subsequent commits per author and then rebase that result on top of master This will retain the author info and reduce the noise in the history log a bit.
> 
> If we would have worked through PRs then history would have looked more or less like this. Most features or commits are squashed into one and then put on top of master.
> 
> Any opinions or can I go ahead with this? Like last time I will then create a new branch that we can switch to once done.

I'm all for starting with squashing to per author commits to reduce noise and then see where that gets us.  It's not helping to have the master not frozen and ask people instead submit PR's against this branch.

2023-09-02 09:31 UTC, DEV-byoos commented
hello devs

In response @ jekkos, I propose to discoss the CI3 master from the ci4-upgrade branch and create a new repository so that the OSPOS based on CI4 is independent of that of CI3.
PS, I did not abandon the project only I coded a new interface based on CI4 adminkit and CI4 modular and propose this as a new UI interface, good to evaluate by following the link http://byoosdigital.xyz/ci4modular
login admin@gmail.com
password 12345678

I still have a little bug left on the management of access rights to the menus

adminkit supports bootstrap 5.3.0
https://github.com/gheav/CI4-StarterPanel
https://github.com/XXPerez/Codeigniter4Modular
quickly I attach the source of the CI4modular and adminkit merger
bye
Gabriel

2023-09-04 14:25 UTC, objecttothis commented
> @objecttothis @SteveIreland I was playing around with the Register this morning and included the buttons that were suggested for the earlier version. I will Upload the Register code if anyone is interested? It appears to be easier then using the old dropdown. The lower 3 buttons only show after a Customer is added to the Sale.
> 
> ![2023-05-16 17_59_08-Window](https://user-images.githubusercontent.com/10962177/238797470-4bf7d7a0-215f-4511-8e82-f18c71a355d2.png)

@odiea sorry If I or others never replied.  I think this would be better as a separate PR after this PR has been merged.  You can feel free to create a branch off this branch or just wait until it has been merged into the master.

2023-09-04 18:43 UTC, odiea commented
@objecttothis all those changes were removed after a bad merge from Master.

2023-09-18 19:47 UTC, jekkos commented
I did not realize that PHP7.4 is end of life already since beginning of this year. https://www.php.net/supported-versions.php

2023-09-19 09:14 UTC, objecttothis commented
> I did not realize that PHP7.4 is end of life already since beginning of this year. https://www.php.net/supported-versions.php

Yeah, it's not even in any of the repos anymore for download.  I think we need to make sure to test this release against all current versions of PHP. At the time of writing, 8.2.9.

2023-09-25 06:53 UTC, objecttothis requested changes

2023-09-25 06:53 UTC, objecttothis commented on app/Controllers/Config.php
> +			if(!isset($this->encrypter))
This shouldn't be necessary because of the block of code starting on line 73.  Does it not work without it?

2023-09-25 07:06 UTC, owlbrudder commented on app/Controllers/Config.php
> +			if(!isset($this->encrypter))
Like you, I expected the initial call to set up the instance and I was very surprised when the system crashed without this additional code. From memory it was another case where $config[] did not return the expected result during check_encryption at line 74 so the call failed and and the encrypter was not instantiated. It seems the $config[] problem was resolved internally after the call at line 74, so calling check_encryption at line 300 succeeded and it was necessary to instantiate the encrypter at that point.

2023-09-25 07:28 UTC, objecttothis commented on app/Controllers/Config.php
> +			if(!isset($this->encrypter))
I'm not seeing where $config[] is being called.  I see config() is being used in the check_encryption function, but that is different.  We likely need to find and fix the bug causing the misbehavior up above... otherwise we are going to end up with bandaids covering broken bones everywhere.

2023-11-01 13:25 UTC, DEV-byoos commented
@objecttothis 
the constant BASEPATH  not exist on CI4,  use FCPATH declared  in /root/index.php

2023-11-01 13:48 UTC, objecttothis commented
> @objecttothis the constant BASEPATH not exist on CI4, use FCPATH declared in /root/index.php

Thank you.  I will replace those instances tomorrow when I am back in the office.

2023-11-01 15:33 UTC, DEV-byoos commented
Thank you @objecttothis for your quick response ho to perfect the fix link the.zip file attached to my message from ********** START debug *************
chapter "company_logo"
Sincerely, Gabriel
[Uploading ci4_upgrade_osposv4-0-0-dev_php8-2.zip…]()

2023-11-02 06:23 UTC, objecttothis commented
@DEV-byoos thank you for the helpful tips.  Please check out ci4-branch, make the changes there and submit a pull request against ci4-branch for these changes. I can do a code review at that time, but wading through the shorthand in your comment is difficult.

2023-11-05 21:20 UTC, jekkos commented
@objecttothis should we reopen the pull request now with the new branch instead?

2023-11-05 21:20 UTC, jekkos commented
@DEV-byoos indeed it might be better if you submit your fixes in a pull request. Do you know how to do that? Thanks!

2023-11-05 21:28 UTC, objecttothis commented
> @objecttothis should we reopen the pull request now with the new branch instead?

I think you can edit this PR so it's ci4-branch trying to merge into master instead of ci4-upgrade. It would be a shame to lose the conversation history in this PR by creating a new one.

2023-11-06 09:18 UTC, DEV-byoos commented
@objecttothis hello,

Well, thank you for your suggestion but I'm not a github boss and my Internet network is weak.
While I get used to the pull-request I suggest sending you patch by patch on "Feature: CodeIgniter 4 upgrade #3592" you can test then update the ci4-upgrade, OK?
like /root/app/controllers/Config.php --- remove_logo method
FIX  rename   remove_logo  with postRemove_logo
code
`	public function postRemove_logo(): void
	{
		$file = FCPATH.'uploads/' . $this->config['company_logo'];
		if (is_readable($file) && unlink($file)) {
			$success = $this->appconfig->save(['company_logo' => '']);
		} else {
			$success = "The file was not found";
		}
		$success = $this->appconfig->save(['company_logo' => '']);
		
		echo json_encode (['success' => $success]);
	}`

2023-11-06 09:25 UTC, objecttothis commented
> @objecttothis hello,
> 
> Well, thank you for your suggestion but I'm not a github boss and my Internet network is weak. While I get used to the pull-request I suggest sending you patch by patch on "Feature: CodeIgniter 4 upgrade #3592" you can test then update the ci4-upgrade, OK? like /root/app/controllers/Config.php --- remove_logo method FIX rename remove_logo with postRemove_logo code ` public function postRemove_logo(): void { $file = FCPATH.'uploads/' . $this->config['company_logo']; if (is_readable($file) && unlink($file)) { $success = $this->appconfig->save(['company_logo' => '']); } else { $success = "The file was not found"; } $success = $this->appconfig->save(['company_logo' => '']);
> 
> ```
> 	echo json_encode (['success' => $success]);
> }`
> ```

@owlbrudder @jekkos do either of you want to take the time to look through @DEV-byoos changes and implement them?  @DEV-byoos I'm working through fixing some problems with attributes right now. I'm sorry, but I just don't have time to submit these changes myself.  The formatting does not come through very well in github because you aren't using `\`\`\`` before and after your code blocks. Your changes are probably very helpful, but I can't get to it. I don't know what your first language is, but I recommend reading a tutorial on how to create a branch, make changes and submit them as a pull request.  You can even do these by hand in Github if you need to.

2023-11-06 09:34 UTC, owlbrudder commented
This looks like something I could use to get back into working state. I am
near end of day here, but I could have a look at it in the morning if
that's okay?

On Mon, 6 Nov 2023, 5:25 pm objecttothis, ***@***.***> wrote:

> @objecttothis <https://github.com/objecttothis> hello,
>
> Well, thank you for your suggestion but I'm not a github boss and my
> Internet network is weak. While I get used to the pull-request I suggest
> sending you patch by patch on "Feature: CodeIgniter 4 upgrade #3592
> <https://github.com/opensourcepos/opensourcepos/pull/3592>" you can test
> then update the ci4-upgrade, OK? like /root/app/controllers/Config.php ---
> remove_logo method FIX rename remove_logo with postRemove_logo code `
> public function postRemove_logo(): void { $file = FCPATH.'uploads/' .
> $this->config['company_logo']; if (is_readable($file) && unlink($file)) {
> $success = $this->appconfig->save(['company_logo' => '']); } else {
> $success = "The file was not found"; } $success =
> $this->appconfig->save(['company_logo' => '']);
>
> 	echo json_encode (['success' => $success]);
> }`
>
> @owlbrudder <https://github.com/owlbrudder> @jekkos
> <https://github.com/jekkos> do either of you want to take the time to
> look through @DEV-byoos <https://github.com/DEV-byoos> changes and
> implement them? @DEV-byoos <https://github.com/DEV-byoos> I'm working
> through fixing some problems with attributes right now. I'm sorry, but I
> just don't have time to submit these changes myself. The formatting does
> not come through very well in github because you aren't using \``` before
> and after your code blocks. Your changes are probably very helpful, but I
> can't get to it. I don't know what your first language is, but I recommend
> reading a tutorial on how to create a branch, make changes and submit them
> as a pull request. You can even do these by hand in Github if you need to.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opensourcepos/opensourcepos/pull/3592#issuecomment-1794396693>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE2THY7F5ODY2MCVURT75JLYDCUIBAVCNFSM6AAAAAAR7HQVR2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJUGM4TMNRZGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-06 11:07 UTC, owlbrudder commented
Thanks for the explanation. I will look at it all in the morning and get
back to you.

On Mon, 6 Nov 2023, 6:58 pm BYOOS, ***@***.***> wrote:

> thanks @owlbrudder <https://github.com/owlbrudder>
>
> following explanation:
> the company_logo config option allows you to replace the OSPOS logo with
> the company logo, OK
>
>    1.
>
>    Add company logo YES
>    2.
>
>    validate the config modification YES after fix
>    3.
>
>    delete the logo NO because it does not disappear on disk, only in the
>    database TABLE ospos_app_config KEY company_logo
>    4.
>
>    if we reload a new company logo the name on the disk will be indexed
>    filename_1...
>    NOTE company logo can only be loaded once.
>    ike /root/app/controllers/Config.php --- remove_logo method
>    FIX rename remove_logo with postRemove_logo
>    code
>    ` public function postRemove_logo(): void
>    {
>    $file = FCPATH.'uploads/' . $this->config['company_logo'];
>    if (is_readable($file) && unlink($file)) {
>    $success = $this->appconfig->save(['company_logo' => '']);
>    } else {
>    $success = "The file was not found";
>    }
>    $success = $this->appconfig->save(['company_logo' => '']);
>
>     echo json_encode (['success' => $success]);
>
>    }`
>
> PS I use code tags, I don't understand why it's buggy???
> best regards
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opensourcepos/opensourcepos/pull/3592#issuecomment-1794562182>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE2THYZTRA4FSMUUJURYCFTYDC7G3AVCNFSM6AAAAAAR7HQVR2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJUGU3DEMJYGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-06 16:40 UTC, DEV-byoos commented
@DEV-byoos indeed it might be better if you submit your fixes in a pull request. Do you know how to do that? Thanks!

Answer   @DEV-byoos
@jekkos
en fait je n'utilise GITHUB seulement pour mes dépôts ou fork et le téléchargement de projet ho mais je vais essayer de trouver un bon tuto pour apprendre cela.

2023-11-06 16:49 UTC, jekkos commented
> 4\. if we reload a new company logo the name on the disk will be indexed filename_1...
>         NOTE company logo can only be loaded once.
>         Like /root/app/controllers/Config.php --- remove_logo method
>         FIX rename remove_logo with postRemove_logo
>         code

Ca sera bon si tu apprendrais a faire un requet tirer. Ou autrement vous pouvez justement envoyer un diff generé par git. Je pense que ca va etre plus facile a inspecter;

2023-11-06 16:56 UTC, jekkos commented
> > @objecttothis should we reopen the pull request now with the new branch instead?
> 
> I think you can edit this PR so it's ci4-branch trying to merge into master instead of ci4-upgrade. It would be a shame to lose the conversation history in this PR by creating a new one.

I checked this, you can only change the target branch, but not the source. Which might make sense. The conflicts we see here are resolved in the other branch. I can copy the content of the issue list here to a new PR. 
The history will remain then in this conversation, in my opinion it has become already a bit too long.

2023-11-06 16:57 UTC, jekkos commented
> DAY 1 thanks @owlbrudder
> 
> following explanation: the company_logo config option allows you to replace the OSPOS logo with the company logo, OK
> 
>     1. Add company logo YES
> 
>     2. validate the config modification YES after fix
> 
>     3. delete the logo NO because it does not disappear on disk, only in the database TABLE ospos_app_config KEY company_logo
> 
>     4. if we reload a new company logo the name on the disk will be indexed filename_1...
>        NOTE company logo can only be loaded once.
>        Like /root/app/controllers/Config.php --- remove_logo method
>        FIX rename remove_logo with postRemove_logo
>        code
> 
> 
> ```
>   	public function postRemove_logo(): void
> 	{
> 		$file = FCPATH.'uploads/' . $this->config['company_logo'];
> 		if (is_readable($file) && unlink($file)) {
> 			$success = $this->appconfig->save(['company_logo' => '']);
> 		} else {
> 			$success = "The file was not found";
> 		}
> 		$success = $this->appconfig->save(['company_logo' => '']);
> 		
> 		echo json_encode (['success' => $success]);
> 	}
> ```
> 
> PS I use code tags, I don't understand why it's buggy??? best regards

Thanks for the proposition. Regarding the function rename, I would not mix camelcase with snake case. In this case camelcase is the way to go.

2023-11-06 17:41 UTC, DEV-byoos commented
DAY 2
thanks @owlbrudder

following explanation:
updating the company logo in its original version works but generates two critical errors in php 8.2 -- php8.3
let me explain ho, it all starts with the info_config.php form
```<?php echo form_open('config/saveInfo/', ```
when validating "change image" on POST to controller /root/app/Controllers/Config.php postSaveInfo method

1) ``` $upload_success = !empty($upload_data['error']);``` the variable $upload_success is not loaded ( !isset ) and causes a critical error on line 357 ``` $message = $upload_success ? $message: strip_tags($upload_data['error']);```
fix in upload_logo method.

coded
``` private function upload_logo(): array
{
helper(['form']);
$validation_rule = [
'company_logo' => [
'label' => 'Company logo',
'rules' => [
'uploaded[company_logo]',
'is_image[company_logo]',
'max_size[company_logo,1024]',
'mime_in[company_logo,image/png,image/jpg,image/gif]',
'ext_in[company_logo,png,jpg,gif]',
'max_dims[company_logo,800,680]',
]
]
];

if (!$this->validate($validation_rule))
{
return (['error' => $this->validator->getError('company_logo')]);
}
else
{
$file = $this->request->getFile('company_logo');

$file_info = [
'orig_name' => $file->getClientName(),
'raw_name' => $file->getName(),
'file_ext' => $file->guessExtension(),
'error' => ''
];

if (! $file->hasMoved()) {
$file->move(FCPATH.'uploads/');
$success = $this->appconfig->save(['company_logo' => $file->getClientName()]);
}

return ($file_info);
}
}```
the $file_info = [...] block is moved up and an 'error' key is added to initialize the value to empty.
I hope this will be clear enough because I'm doing it with what I have.
bye see you tomorrow

2023-11-06 18:18 UTC, objecttothis commented
@DEV-byoos this comment section is going to get long and chaotic. Please use Element (formerly glitter). You can use their online client or download a client on their website (https://matrix.org/ecosystem/clients/element/) just change the server to `gitter.im`. I will send you an invite to the dev room of opensourcepos. Just use your GitHub account to login.

2023-11-07 06:58 UTC, objecttothis commented
I'm closing this PR as it will not be one we will merge.  See #3858

2023-11-07 06:58 UTC, closed without merging