Clean up work on reports listing view and lang() methods
opensourcepos/opensourcepos pull request #3707
Opened 2023-03-05 10:04 UTC by edwinbsmith

* added a little logic into the Reports controller
* simplified the helper methods in the reports_helper file
* fixed the lang() calls to be consistent with the en-US format of language keys

The links to some of the detailed reports are returning a 404. I don't know if that's a result of the changes in the code or they are not complete yet. For example `/reports/detailed_sales` works but `/reports/specific_suppliers` returns a 404. `/reports/specific_supplier` does not 404 but outputs an error in the Reports controller.

2023-03-05 11:28 UTC, objecttothis commented
The 404 errors when you click on the links are likely due to routing errors.

2023-03-05 12:14 UTC, objecttothis requested changes

2023-03-05 12:14 UTC, objecttothis commented on app/Views/reports/listing.php
> +				<?php foreach ($permission_ids as $permission_id) :
For consistency with the rest of the code we need to stick to { } notation rather than : .

2023-03-05 12:14 UTC, objecttothis commented on app/Views/reports/listing.php
> +					<a class="list-group-item" href="<?php echo $inventory_low_report['path']; ?>"><?php echo $inventory_low_report['label']; ?></a>
Let's replace all these with short notation, so `<?= $foobar ?>`

2023-03-05 12:17 UTC, jekkos commented on app/Helpers/report_helper.php
> +	if ($lang_key === '') {
it would be cool if we could run some kind of formatting check within CI to check for code style conventions

2023-03-05 12:19 UTC, jekkos commented on app/Helpers/report_helper.php
> +	return true;
@objecttothis wasn't CI3 having boolean uppercase convention? Does that still hold with CI4?

2023-03-05 12:20 UTC, objecttothis commented on app/Helpers/report_helper.php
> +	return true;
All the examples in their code are all lowercase

2023-03-05 12:21 UTC, objecttothis commented on app/Helpers/report_helper.php
> +	return true;
> @objecttothis wasn't CI3 having boolean uppercase convention? Does that still hold with CI4?

Also in their documentation examples.

2023-03-05 19:09 UTC, objecttothis commented on app/Helpers/report_helper.php
> +	if ($lang_key === '') {
I noticed that the codeigniter repo has a code style check as part of their build process. So it's possible. I'm not well experienced with the DevOps side, so I'm not sure the best way to do it. @edwinbsmith have you done much DevOps stuff?

2023-03-08 16:39 UTC, edwinbsmith commented on app/Helpers/report_helper.php
> +	if ($report_prefix !== '') {
@objecttothis checking on this... according to the CI4 style guide [here](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/styleguide.md#control-structures), there should be one space between the closing parenthesis and the opening brace. Similarly, I ran the coding standard cleanup script on my files [here](https://github.com/CodeIgniter/coding-standard) and it didn't flag or change the brackets.

I don't mind updating the brackets, just wanted to double check on the requirement.

2023-03-08 16:40 UTC, edwinbsmith commented on app/Helpers/report_helper.php
> +function can_show_report($permission_id, array $restrict_views = [])
added

2023-03-08 16:59 UTC, objecttothis commented on app/Helpers/report_helper.php
> +	if ($report_prefix !== '') {
Yeah, the requirement is not a ci coding standard and specific to this project. I don't mind adopting a singular coding standard, but it should be the same across the code base... If we adopt a different coding standard, I think we should put it in a separate PR.

That said, I think there are a couple of things we can do.  One would be a code style check in the build. The other is to maintain an EditorConfig file in the repo.  This file will get picked up by most IDEs and configure things like tabs, etc.

2023-03-09 06:31 UTC, edwinbsmith commented on app/Helpers/report_helper.php
> +	if ($report_prefix !== '') {
In the meantime, I've updated the brackets.

2023-03-09 06:32 UTC, edwinbsmith commented
Alright @objecttothis, I think this PR is cleaned up style wise!

2023-09-29 08:49 UTC, objecttothis approved these changes

2023-09-29 08:52 UTC, merged