Assignable Keyboard Shortcuts Updates
opensourcepos/opensourcepos pull request #3720
Opened 2023-03-18 12:38 UTC by WebShells

Few updates regarding HotKeys/ Keyboard Shortcut section.

. Added Shortcut TAB under config section where user can re-assign the shortcuts as needed
. Shortcuts Help Modal in Sales Register now reflects the assigned shortcuts
. Updates JS section in register in order to retreive assigned keys from database.

To be fixed:
. Migration file
. Success message on submit

2023-03-18 19:31 UTC, jekkos commented on application/libraries/Sale_lib.php
> +		$key_shortcuts['27 | ESC'] = $this->CI->lang->line('sales_key_1');
this can be done in a loop

2023-03-18 19:33 UTC, jekkos commented
@WebShells we might want to freeze master branch until the CI4 upgrade is done, merging this now will only create more conflicts later on. Any new functionality should be built on top of CI4.

2023-03-18 21:50 UTC, WebShells commented
> @WebShells we might want to freeze master branch until the CI4 upgrade is done, merging this now will only create more conflicts later on. Any new functionality should be built on top of CI4.

@jekkos do you want me to apply the changes to fit to CI4 upgrade and submit the PR to that branch ? or shall i wait till the upgrade is done ?

2023-03-19 06:54 UTC, objecttothis commented
> > @WebShells we might want to freeze master branch until the CI4 upgrade is done, merging this now will only create more conflicts later on. Any new functionality should be built on top of CI4.
> 
> @jekkos do you want me to apply the changes to fit to CI4 upgrade and submit the PR to that branch ? or shall i wait till the upgrade is done ? 

I recommend we still set this PR to merge with the master but write the changes to work with CI4. Then it will be ready to test/merge after the CI4 branch has been merged into the master.

I agree that the master branch needs to be frozen.

2023-03-25 11:37 UTC, jekkos commented on application/libraries/Sale_lib.php
> +		$key_shortcuts = array();
What could be cleaner here is to approach this in OOP fashion and have a proper `Shortcut` class or a central dict, that has a couple of fields like `keycode`, `lang_line`. Then most of the repetitive parts in this code can be generated dynamically, by filling in the correct variable at every step

2023-03-25 11:38 UTC, jekkos commented on application/views/sales/help.php
>  					<td><?php echo $this->lang->line('sales_key_cancel'); ?></td>
here you would have one loop going over the datastructure and printing the rows in generic fashion

2023-03-25 11:41 UTC, jekkos commented
> > > @WebShells we might want to freeze master branch until the CI4 upgrade is done, merging this now will only create more conflicts later on. Any new functionality should be built on top of CI4.
> > 
> > 
> > @jekkos do you want me to apply the changes to fit to CI4 upgrade and submit the PR to that branch ? or shall i wait till the upgrade is done ?
> 
> I recommend we still set this PR to merge with the master but write the changes to work with CI4. Then it will be ready to test/merge after the CI4 branch has been merged into the master.
> 
> I agree that the master branch needs to be frozen.

Fine by me, I guess this won't be a big one. But we need a migration at least otherwise there might be issues in the register @WebShells

2023-03-31 13:58 UTC, WebShells commented
> Fine by me, I guess this won't be a big one. But we need a migration at least otherwise there might be issues in the register @WebShells

Added.

2023-03-31 14:34 UTC, objecttothis requested changes
Super.  Once #3592 is merged with the master you'll need to modify these changes to CI4 formatting and then we can approve and merge.  If you want to get a head start, you can take a look at these files in the ci4-upgrade branch and change it now.

2025-03-31 08:32 UTC, objecttothis commented
@WebShells now that CI4 has been merged into the master can you rebase these changes?

2026-03-11 12:48 UTC, objecttothis commented
@WebShells do you want to bring this branch up to date with the master and take a look at the review comments so we can merge this PR?

2026-05-05 22:54 UTC, WebShells commented
> @WebShells do you want to bring this branch up to date with the master and take a look at the review comments so we can merge this PR?

Ill handle that @objecttothis

2026-05-06 04:27 UTC, WebShells commented
@jekkos @objecttothis am going to close this PR As i already submitted an updated version on #4532.

2026-05-06 04:27 UTC, closed without merging