Ci4 enhancement use writable backup
opensourcepos/opensourcepos pull request #3815
Opened 2023-09-11 23:21 UTC by owlbrudder

2023-09-12 06:34 UTC, objecttothis requested changes

2023-09-12 06:34 UTC, objecttothis commented on app/Helpers/security_helper.php
> +		$backup_path = ROOTPATH . '/writable/backup/.env.bak';
This is incorrect.  It should be `$backup_path = WRITEPATH . '/backup/.env.bak';`

https://codeigniter.com/user_guide/general/common_functions.html#WRITEPATH

2023-09-12 06:34 UTC, objecttothis commented on app/Helpers/security_helper.php
> +		$new_config_path = ROOTPATH . '/writable/backup/.env' ;
WRITEPATH here rather than ROOTPATH

2023-09-12 06:34 UTC, objecttothis commented on app/Helpers/security_helper.php
> +		if(strtolower(class_basename($controller)) == 'login')
Let's add a blank line between the if statement and variable declarations.

2023-09-12 06:34 UTC, objecttothis commented on app/Helpers/security_helper.php
> +			$handle = @fopen($new_config_path, 'w+') or die("Unable to open " . $new_config_path . " for writing");
Generally, you don't want to use " in php unless you are using string interpolation because it causes php to parse what you have between quotes. It's not a huge deal here, but in a loop with many iterations it adds up.

Let's use string interpolation where possible though, so this should become 
`die("Unable to open $new_config_path for writing");`

2023-09-12 06:34 UTC, objecttothis commented on app/Helpers/security_helper.php
> +		$new_config_path = ROOTPATH . '/writable/backup/.env' ;
Also, you don't have to do this, but I would declare $new_config_path up above with $backup_path and $config_path.

2023-09-12 06:34 UTC, objecttothis commented on app/Helpers/security_helper.php
> +			$handle = @fopen($new_config_path, 'w+') or die("Unable to open " . $new_config_path . " for writing");
Rather than killing the process with die() and a message, we need to write this to the OSPOS log using log_message(). https://codeigniter.com/user_guide/general/common_functions.html#log_message. Any messages that we send to the user need to be sent to the view to be gentrified. in the login view you can see this on lines 50-53 with has errors.... though I don't know if you will be able to use CI4 validation or not... look into whether you can add an error programmatically in the code using Services::validation().  If so, all you need to do is that before calling the view.

2023-09-12 06:34 UTC, objecttothis commented on app/Helpers/security_helper.php
> +			echo ' alert("File ' . $new_config_path . ' has been created. You must move this to ' . ROOTPATH . '")';
Same as above.  This needs to be sent to the view. Take a look at the login view and see how the message regarding needed migrations are done.

This is the reason that we had given write access to Apache to the folder. This method requires the user to manually move the file after from the writepath to baseurl. How about we try a hybrid:
1- backup the file to the writepath backup folder with a copy.
2- modify the .env file in baseurl.
3- Send the message to the view that the backup and modification occurred.

This way Apache doesn't need write permission to the baseurl, just to .env... Potentially this does still have security implications, but regardless, Apache does need to have read permission on that directory regardless.

@jekkos, do you have thoughts on the best way to approach this?

2023-09-12 06:34 UTC, objecttothis commented on app/Helpers/security_helper.php
> +	$new_config_path = ROOTPATH . '/writable/backup/.env' ;
use WRITEPATH in these lines too.

2023-09-14 09:04 UTC, objecttothis requested changes
Let's talk if any of my comments are unclear or you think I didn't understand the whole picture... that's possible too.

2023-09-14 09:04 UTC, objecttothis commented on app/Helpers/security_helper.php
> +		log_message('error', "Unable to open $config_path for updating");
This log message doesn't seem to match what the function is doing.  I think the message should explain that it was unable to abort the encryption conversion or something related to not being able to revert the encryption conversion.

2023-09-14 09:04 UTC, objecttothis commented on app/Helpers/security_helper.php
> +		fwrite($handle, $config_file) === FALSE;
I don't have time to download and test this line, but I think this will return a boolean but there isn't anything done with the boolean.  Should this be in an if statement?

2023-09-15 08:37 UTC, objecttothis requested changes

2023-09-15 08:37 UTC, objecttothis commented on app/Helpers/security_helper.php
> +	if((empty($old_key)) or (strlen($old_key) < 64))
I had to look this one up, but when it doesn't matter about using `or` and `||`, lets use `||`.

Taken from the php documentation, the `||` has higher precedence than `or`, so when it matters `or` can do different thing than we are expecting.  In this case, it doesn't matter, unless I'm missing something. If it doesn't make a difference, let's keep the operator usage the same as the rest of the code and use `||`.

2023-09-15 08:37 UTC, objecttothis commented on app/Helpers/security_helper.php
> +		@chmod($config_path, 0770);
Looks like this was already done on line 30.  Did you mean to return the permissions back to 0640? in the end, our .env file should be writable by the owner, readable by Apache (group) and not readable by world. The only downside to doing that is that we wouldn't be able to programmatically modify .env in the future.

2023-09-15 08:37 UTC, objecttothis commented on app/Helpers/security_helper.php
> +		$retval = fwrite($handle, $config_file);
To make the code more readable, don't abbreviate variable names unless it's a word in common usage and use variable names detailing what it contains.  So in this case `$config_file` is fine because config is a word in common usage, but let's refactor `$retval` because neither ret nor val are used commonly and return_value is too generic. 

If instead, you refactor this variable to $write_succeeded then line 55 below becomes `if($write_succeeded === false)`

Even better would be to write this as `$write_failed = !fwrite($handle, $config_file);`
Then write line 55 as `if($write_failed)`

Make sense?

2023-09-15 08:37 UTC, objecttothis commented on app/Helpers/security_helper.php
> +		if($retval === false)
same thing here as above regarding $retval

2023-09-15 08:37 UTC, objecttothis commented on app/Helpers/security_helper.php
> +		log_message('info', "File $config_path has been updated to undo encryption conversion");
This is going to fire even if the log message above it gets written but they seem to say conflicting things. The log message on 89 makes sense however if fwrite fails on line 82, I don't think it should get to that point. Rather than put an else statement here, though we could just put a return statement between lines 87 and 88 inside the if statement.

2023-09-15 08:41 UTC, objecttothis commented on app/Helpers/security_helper.php
> +		log_message('info', "File $config_path has been updated to undo encryption conversion");
Looking back at my comments earlier, I had you remove that 2nd else, but did not intend on you removing the return statement inside the if as well... just add the return statement back into the if.

2023-09-15 08:56 UTC, jekkos commented on app/Helpers/security_helper.php
> +		//Attempt to make these files writable
You can add some comments in the PR instead

2023-09-15 08:57 UTC, jekkos commented on app/Helpers/security_helper.php
>  		@chmod($backup_path, 0770);
660 is not enough? Having the exec bit set might be a security issue

2023-09-15 08:59 UTC, jekkos commented on app/Helpers/security_helper.php
> +	if((empty($old_key)) or (strlen($old_key) < 64))
Indeed cosistency would be nice

2023-09-15 09:00 UTC, jekkos commented on app/Helpers/security_helper.php
> +			//we could return false at this point,
Indeed comments are seldomly required, only if code cannot explain itself

2023-09-15 09:51 UTC, objecttothis commented on app/Helpers/security_helper.php
>  		@chmod($backup_path, 0770);
> 660 is not enough? Having the exec bit set might be a security issue

Good point.  @owlbrudder since this is a file and not something that needs to be executed, we should be able to get by with just 0660 permissions.  I think default best practice for files anyway is 640.

2023-09-15 09:53 UTC, objecttothis commented on app/Helpers/security_helper.php
> +			//we could return false at this point,
> Indeed comments are seldomly required, only if code cannot explain itself

Yeah, he fixed it already in the code.

2023-09-16 02:21 UTC, owlbrudder commented on app/Helpers/security_helper.php
> +	if((empty($old_key)) or (strlen($old_key) < 64))
Yep, fully agree - I winced when you pointed that out because I normally use ||.

2023-09-16 02:21 UTC, owlbrudder commented on app/Helpers/security_helper.php
> +		@chmod($config_path, 0770);
I am developing in my home directory, so I need read/write on everything and apache is my group user so apache needs read on everything plus write on writable/* and on .env, but you are correct - I can't think of any reason to give execute permissions anywhere around the OSPOS landscape. We have no scripts etc needing execute permissions, do we? I will keep .env and the writable tree at 660 if that's okay and the rest of the tree can be 640.

2023-09-16 02:21 UTC, owlbrudder commented on app/Helpers/security_helper.php
> +		$retval = fwrite($handle, $config_file);
Yes, I like that. retval is a relic from my C programming days when we had to fit an entire application into a 32kb ROM, so we pruned everything to the max and that lead to terse code with equally terse identifiers. No valid reason for it - thanks for the upgrade to my thinking.

2023-09-16 02:21 UTC, owlbrudder commented on app/Helpers/security_helper.php
> +		if($retval === false)
Yep - I like it.

2023-09-16 02:21 UTC, owlbrudder commented on app/Helpers/security_helper.php
> +		log_message('info', "File $config_path has been updated to undo encryption conversion");
Bahaha - mea culpa. I must have removed the return statement I had sitting after the first message for reasons I will blame on sore eyes but for which I have no real excuse!

2023-09-16 02:21 UTC, owlbrudder commented on app/Helpers/security_helper.php
>  		@chmod($backup_path, 0770);
Agreed - as above.

2023-09-18 19:49 UTC, jekkos commented on app/Helpers/security_helper.php
> +		@chmod($backup_path, 0660);
if we set the writable flag for the .env only for this request, then I guess fine

2023-09-18 20:08 UTC, jekkos commented
@owlbrudder It looks like all comments were addressed here? Do you know if we also remove the backup once the encryption key is set? It might be best to do so to avoid any potential leaks of application credentials

2023-09-18 20:18 UTC, jekkos approved these changes

2023-09-18 22:54 UTC, owlbrudder commented
I agree that the security problem needs to be addressed. As mentioned
elsewhere, the backup of .env only exists to support a single method in
security_helper.php which reverses the attempt to apply an encryption key.
That method is called only by a single migration script at this time. I
suggest adding a 'delete_backup()' method to security_helper and modifying
the migration script to call this method when it has completed wherever
else it is doing.

On Tue, Sep 19, 2023, 4:09 AM jekkos ***@***.***> wrote:

> @owlbrudder <https://github.com/owlbrudder> It looks like all comments
> were addressed here? Do you know if we also remove the backup once the
> encryption key is set? It might be best to do so to avoid any potential
> leaks of application credentials
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opensourcepos/opensourcepos/pull/3815#issuecomment-1724295625>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE2THY2QKKIAVBHQ5SY4LU3X3CS55ANCNFSM6AAAAAA4UBAQ6A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-19 09:15 UTC, objecttothis approved these changes

2023-09-19 09:15 UTC, merged

2023-09-19 21:50 UTC, jekkos commented
I have added this followup ticket: https://github.com/opensourcepos/opensourcepos/issues/3826