Handle missing mailchimp api key
opensourcepos/opensourcepos pull request #3816
Opened 2023-09-12 00:24 UTC by owlbrudder

Wrap calls to extract the key in defensive code so the system responds gracefully if the key is not set, instead of crashing

2023-09-12 06:45 UTC, objecttothis requested changes

2023-09-12 06:45 UTC, objecttothis commented on app/Controllers/Config.php
When naming the Pull Request please add "CI4: Bugfix" or "CI4: Enhancement" as a suffix.

2023-09-12 06:45 UTC, objecttothis commented on app/Controllers/Config.php
> +			if(isset($this->config['mailchimp_api_key']))
Let's convert this to ternary notation. It's a lot cleaner
```
$mailchim_api_key = isset($this->config['mailchimp_api_key'])
    ? $this->config['mailchimp_api_key'];
	: '';
```

2023-09-12 06:45 UTC, objecttothis commented on app/Controllers/Config.php
> +			//If mailchimp_list_id has not been configured react gracefully
Same here with ternary notation.

2023-09-12 06:45 UTC, objecttothis commented on app/Libraries/Mailchimp_lib.php
> +		//If mailchimp_api_key has not been configured react gracefully
and here with ternary notation.

2023-09-14 10:08 UTC, objecttothis commented on app/Libraries/Mailchimp_lib.php
> +			: '';
Was the if statement below puking without this? I would think that empty() would report true if the API key isn't set.

2023-09-14 10:29 UTC, owlbrudder commented on app/Controllers/Config.php
> +			$mailchimp_api_key = isset($this->config['mailchimp_api_key'])
The problem is the attempt to get the nonexistant config['mailchimp_api_key'] throws an error before the assignment takes place, so you are correct in principle but the actual error I had to defend against was unexpected. Your solution is how I expected the code to work, but it does not.

2023-09-14 10:30 UTC, owlbrudder commented on app/Libraries/Mailchimp_lib.php
> +			: '';
As above, the problem is the attempt to get the nonexistant config['mailchimp_api_key'] throws an error before the assignment takes place. This change is needed to let the code proceed.

2023-09-14 10:44 UTC, objecttothis commented on app/Controllers/Config.php
> +			$mailchimp_api_key = isset($this->config['mailchimp_api_key'])
OK, even if you have to have `isset()` you can combine your ternary operators
```
$mailchimp_api_key = $this->config['mailchimp_api_key']
$mailchimp_api_key = !empty($mailchimp_api_key) && isset($mailchimp_api_key)
	? $this->encrypter->decrypt($mailchimp_api_key)
	: '';
```

2023-09-14 11:40 UTC, owlbrudder commented on app/Controllers/Config.php
> +			$mailchimp_api_key = isset($this->config['mailchimp_api_key'])
Sorry, I did not explain myself clearly. The error is produced by invoking $this->config['mailchimp_api_key'] and the process fails before assignment of the result. The ternary would have to be: something like this (untested):

$mailchimp_api_key = empty($this->config['mailchimp_api_key'])
	? ''
	: $this->encrypter->decrypt($this->config['mailchimp_api_key']);

It eliminates the need for the isset() test, is about as compact as I can get it and should work fine. If you agree, I will rework all the ternaries accordingly.

2023-09-15 09:01 UTC, objecttothis requested changes
Just the one change.

2023-09-15 09:48 UTC, objecttothis commented on app/Controllers/Config.php
> +			$mailchimp_api_key = isset($this->config['mailchimp_api_key'])
> Sorry, I did not explain myself clearly. The error is produced by invoking $this->config['mailchimp_api_key'] when such a value does not exist and the process fails before assignment of the result. The ternary would have to be: something like this (untested):
> 
> $mailchimp_api_key = ! isset($this->config['mailchimp_api_key']) ? '' : $this->encrypter->decrypt($this->config['mailchimp_api_key']);
> 
> isset() returns false if the variable does not exist, has been unset, or if it has a null value. The above is about as compact as I can get it and seems to work fine.

That's fine.  Just flip it around though, like I wrote in the code review
```
$mailchimp_api_key = isset($this->config['mailchimp_api_key'])
? $this->encrypter->decrypt($this->config['mailchimp_api_key'])
: '';
```

2023-09-16 01:48 UTC, owlbrudder commented on app/Controllers/Config.php
> +			$mailchimp_api_key = !isset($this->config['mailchimp_api_key'])
I debated with myself before sending them like that. The fact is 99.99% of the time the variable will be set, so your correction results in a more efficient execution path. I'll flip 'em and ship 'em now.

2023-09-16 06:35 UTC, objecttothis commented on app/Controllers/Config.php
> +			$mailchimp_api_key = !isset($this->config['mailchimp_api_key'])
Thanks. I haven't done any optimization testing to see whether flipped would process faster. In this case, since it isn't a loop over 1000's of iterations, let's go for the more readable and consistent with the rest of the code. I'll take a look at these pull requests on Monday. I hope you're feeling better.

2023-09-16 06:36 UTC, merged