Fixed csv import when updating items that have a barcode
opensourcepos/opensourcepos pull request #3988
Opened 2024-05-06 18:53 UTC by SpookedByRoaches

If the item is being updated, the check if there is an existing item with the same barcode does not make sense.

2024-05-11 10:46 UTC, jekkos commented
@SpookedByRoaches I believe there is an option that allows for duplicate barcodes to exist. We probably can not do the update in case this option is enabled, so this should be an extra condition before the update is performed.

2024-05-11 11:58 UTC, jekkos requested changes
Add additional config check for allow duplicate barcodes

2024-05-11 19:46 UTC, SpookedByRoaches commented
Why not do the update in that case? The update applies to the items with the existing Id not the Barcode. You would be right in adding the check for the `$is_failed_row` inside that same block. I can add a check there to allow the duplicate barcode if you want. Let me know if I missed something with what you said.

P.S. Apologies for the garbage commits I'm not too experienced with git. I removed those.

2024-05-13 22:19 UTC, jekkos commented
Ok indeed the `is_update` is set if `item_id > 0`.

2024-05-13 22:19 UTC, merged