Ci4 failed queries
opensourcepos/opensourcepos pull request #4040
Opened 2024-08-03 22:22 UTC by jekkos

2024-08-03 22:26 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> -DROP INDEX `person_id` ON `ospos_customers`;
@objecttothis why not keep the index drop here?

2024-08-03 22:55 UTC, jekkos commented
@SteveIreland @objecttothis good news, the dev server picked up this change and the setup is fine again.
So it went from empty database.sql and ran all the migrations after.

2024-08-04 03:19 UTC, objecttothis commented
Fantastic. I'm on vacation so I can review it when I get back or @SteveIreland can. Have we tested these changes against a 3.3.9 or prior database? I can do it when I get back if not but feel free to merge in the meantime if you feel confident that these changes ultimately result in identical schemas between new dbs and existing.

2024-08-04 10:41 UTC, SteveIreland commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> -DROP INDEX `person_id` ON `ospos_customers`;
That was a brilliance from @objecttothis

2024-08-04 11:04 UTC, objecttothis commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> -DROP INDEX `person_id` ON `ospos_customers`;
It's only brilliance if it works. It should be compatible but we should test it with several versions of MariaDB and MySQL.

2024-08-04 12:28 UTC, jekkos commented
I will try to do the following, upgrade one install from scratch, dump the schema.

Then I will use demo db which is at 3.3.9 and link that to master image and make another dump. Then compare those

2024-08-04 16:50 UTC, SteveIreland commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> -ALTER TABLE `ospos_tax_codes` MODIFY `deleted` tinyint(1) DEFAULT 0 NOT NULL;
Yes, it's still needed.

2024-08-04 17:18 UTC, SteveIreland approved these changes
As mentioned earlier, I'm going to rework a lot of this in order to better log migration progress, but I've already tested most of this and it works in my limited testing.

The only question I have is about changing the data optimization script when it has already been included in the 3.8 and 3.9 release.   Are we coding it so that it can be rerun without breaking anything>

2024-08-04 20:19 UTC, objecttothis commented
> As mentioned earlier, I'm going to rework a lot of this in order to better log migration progress, but I've already tested most of this and it works in my limited testing.
> 
> The only question I have is about changing the data optimization script when it has already been included in the 3.8 and 3.9 release.   Are we coding it so that it can be rerun without breaking anything>

If you look at the code which migrates CI3 migration tables to CI4 migrations tables what you should see is that it transfers over all scripts which have already run, so nothing should ever run twice. That said, for every time we change something in constraints.sql or tables.sql we need to go through all existing scripts related to those changes and refactor the code to bring all permutations of the schema to be the same as a new install which ran migrations to that point. Hence the if statements.

That said I'm pretty nervous about us rewriting scripts because of the risk of differing schemas. If we find a script that put the schema in sub-optimal condition and write a new migration to correct it without touching the original. The exception to this are adding in checks to see if something exists before doing something.

2024-08-04 20:23 UTC, objecttothis commented
The other thing is for 3.4.0 I recommend we only make just enough changes to run migrations bug free and focus instead on working out bugs as well as getting all previous functionality working then release.

2024-08-05 21:02 UTC, jekkos commented
@objecttothis fully agree we should limit changes to older migration scripts as much as possible. In other systems they make those scripts append only. In this case with Mysql 8 we probably have no other choice. I also have the feeling that we will easily introduce new issues and bugs by touching those as there are many different scenarios to test every change against, and we do not have the capacity to deal with all that.

2024-08-12 02:21 UTC, SteveIreland commented
I merged a few changes into this branch.  With these changes I was able to successfully upgrade a 3.3.8 OSPOS to 3.4 in MySQL 5.7 and then upgrade it to MySQL 8.  I was also able to create a new instance of OSPOS directly into MySQL 8.

I confirmed that in both scenarios, after the upgrade was complete the three unnecessary person_id keys were removed from customers, employees, and suppliers.

2024-08-12 09:44 UTC, jekkos commented
Thanks @SteveIreland for the additional work. I see that dev server has tried to deploy the latest commit. It is now failing again the migration due to this error ```Too many keys specified; max 64 keys allowed```

2024-08-12 12:47 UTC, SteveIreland commented
Odd, when all is complete at the most we have 6 indexes on a handful of tables.

So, my guess is that the attribute migration script is dynamically creating indexes and it's so complicated that it doesn't know when to stop.  :-)

I haven't yet created any test data involving attributes, so I'll do that and retest to see if I get the same failure.

2024-08-12 13:05 UTC, objecttothis commented
> Odd, when all is complete at the most we have 6 indexes on a handful of tables.
> 
> So, my guess is that the attribute migration script is dynamically creating indexes and it's so complicated that it doesn't know when to stop. :-)
> 
> I haven't yet created any test data involving attributes, so I'll do that and retest to see if I get the same failure.

I saw this movie.  This is the part where the machines take over and start a war with the humans... or is it make them subservient batteries?  I can never remember.

2024-08-13 02:34 UTC, SteveIreland commented
@jekkos  I added one of each of the attribute types  and ran the upgrade without any issue - so I was unable to identify anything that I can fix.

The Travis log is empty, so I'm not sure where to go with this next (except to revert the migration back to the code that presumably ran successfully in 3.3.9.

Thoughts?

2024-08-15 23:00 UTC, jekkos commented
@SteveIreland I have checked the setup today a bit further, and found two things
* Locally I'm running mariadb 10.5 and the branch seems to start fine
* On dev server I was using an ancient version of docker (build from 2017) and still on 10.1.5. This gave me the 'too many keys` error
* I upgraded docker to latest version on the server and now I can pull MariaDB 10.5 for the build. The error does not appear anymore but I get `Can't DROP INDEX `person_id`; check that it exists `

2024-08-16 18:50 UTC, objecttothis commented
We might need to drop support for older versions of MariaDB.

You can get around the can't drop error by adding a check to make sure it exists before trying to delete it. you can see how I did it in my commits to that branch.

2024-08-16 21:58 UTC, jekkos commented
I have compared both dumps now and see that perosn_id is NOT a primary key in the version that was upgraded from 3.3.9 to 3.4. So in this case we install from the 3.3.9 archive, then switch to the master. @SteveIreland in this scenario, the primary key is not there as the database.sql was updated in master and after 3.3.9 release. We still need to add it if it does not exist in the upgrade script.

2024-08-16 22:02 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> -ALTER TABLE `ospos_customers` ADD PRIMARY KEY(`person_id`);
@SteveIreland @objecttothis it seems that this might be needed in case it's not a primary key yet

2024-08-16 22:02 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> -ALTER TABLE `ospos_employees` ADD PRIMARY KEY(`person_id`);
same for this one

2024-08-16 22:02 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> -ALTER TABLE `ospos_suppliers` ADD PRIMARY KEY(`person_id`);
also so this one

2024-08-16 23:20 UTC, jekkos commented
@SteveIreland I have pushed an extra fix now that checks if primary key exist and then add them in case they do not (as they were not created initially in a 3.3.9 install).

2024-08-20 22:58 UTC, jekkos commented
@SteveIreland your last change deletes person_id indexes again in the fix_keys_for_db_upgrade migrations. @objecttothis did already add these deletions in this migration 20210422000000_database_optimizations.php . Why were they needed again?

2024-08-20 23:04 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> -ALTER TABLE `ospos_tax_codes` MODIFY `deleted` tinyint(1) DEFAULT 0 NOT NULL;
I see there is a diff on this field when I compare upgraded 3.3.9 to 3.4 vs a clean install
* 3.4 clean has int(1) type
* upgraded has tinyint typ

2024-08-20 23:07 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> +ALTER TABLE `ospos_items` DROP FOREIGN KEY `ospos_items_ibfk_1`;
@objecttothis I do see a difference between a version upgraded from 3.3.9 and a clean 3.4 install. The upgraded version has no (item_id, deleted) key while the clean version does have one.

2024-08-20 23:13 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> -ALTER TABLE `ospos_customers` ADD INDEX(`company_name`);
This change also needs to be reverted, there is a diff as well.

2024-08-20 23:16 UTC, jekkos commented
[3.4.txt](https://github.com/user-attachments/files/16683218/3.4.txt)
[3.4-upgraded.txt](https://github.com/user-attachments/files/16683219/3.4-upgraded.txt)

Here the two dumps I made. The differences are quite small but the adaptation of the old script does seem to have created some  issues.

2024-08-20 23:16 UTC, jekkos commented
```
329c329
<   KEY `person_id` (`person_id`),
---
>   PRIMARY KEY (`person_id`),
331a332
>   KEY `company_name` (`company_name`),
454a456
>   PRIMARY KEY (`person_id`),
456d457
<   KEY `person_id` (`person_id`),
520a522
>   KEY `ospos_expenses_ibfk_3` (`supplier_id`),
524d525
<   KEY `ospos_expenses_ibfk_3` (`supplier_id`),
791d791
<   KEY `item_id` (`item_id`,`deleted`),
856,890c856,890
< (1,'20170501150000','App\\Database\\Migrations\\Migration_Upgrade_To_3_1_1','default','App',1724193988,1),
< (2,'20170502221506','App\\Database\\Migrations\\Migration_Sales_Tax_Data','default','App',1724193988,1),
< (3,'20180225100000','App\\Database\\Migrations\\Migration_Upgrade_To_3_2_0','default','App',1724193989,1),
< (4,'20180501100000','App\\Database\\Migrations\\Migration_Upgrade_To_3_2_1','default','App',1724193989,1),
< (5,'20181015100000','App\\Database\\Migrations\\Migration_Attributes','default','App',1724193989,1),
< (6,'20190111270000','App\\Database\\Migrations\\Migration_Upgrade_To_3_3_0','default','App',1724193990,1),
< (7,'20190129212600','App\\Database\\Migrations\\Migration_IndiaGST','default','App',1724193991,1),
< (8,'20190213210000','App\\Database\\Migrations\\Migration_IndiaGST1','default','App',1724193991,1),
< (9,'20190220210000','App\\Database\\Migrations\\Migration_IndiaGST2','default','App',1724193991,1),
< (10,'20190301124900','App\\Database\\Migrations\\Migration_decimal_attribute_type','default','App',1724193991,1),
< (11,'20190317102600','App\\Database\\Migrations\\Migration_add_iso_4217','default','App',1724193991,1),
< (12,'20190427100000','App\\Database\\Migrations\\Migration_PaymentTracking','default','App',1724193991,1),
< (13,'20190502100000','App\\Database\\Migrations\\Migration_RefundTracking','default','App',1724193991,1),
< (14,'20190612100000','App\\Database\\Migrations\\Migration_DBFix','default','App',1724193992,1),
< (15,'20190615100000','App\\Database\\Migrations\\Migration_fix_attribute_datetime','default','App',1724193992,1),
< (16,'20190712150200','App\\Database\\Migrations\\Migration_fix_empty_reports','default','App',1724193992,1),
< (17,'20191008100000','App\\Database\\Migrations\\Migration_receipttaxindicator','default','App',1724193992,1),
< (18,'20191231100000','App\\Database\\Migrations\\Migration_PaymentDateFix','default','App',1724193992,1),
< (19,'20200125100000','App\\Database\\Migrations\\Migration_SalesChangePrice','default','App',1724193992,1),
< (20,'20200202000000','App\\Database\\Migrations\\Migration_TaxAmount','default','App',1724193992,1),
< (21,'20200215100000','App\\Database\\Migrations\\Migration_taxgroupconstraint','default','App',1724193992,1),
< (22,'20200508000000','App\\Database\\Migrations\\Migration_image_upload_defaults','default','App',1724193992,1),
< (23,'20200819000000','App\\Database\\Migrations\\Migration_modify_attr_links_constraint','default','App',1724193992,1),
< (24,'20201108100000','App\\Database\\Migrations\\Migration_cashrounding','default','App',1724193992,1),
< (25,'20201110000000','App\\Database\\Migrations\\Migration_add_item_kit_number','default','App',1724193992,1),
< (26,'20210103000000','App\\Database\\Migrations\\Migration_modify_session_datatype','default','App',1724193992,1),
< (27,'20210422000000','App\\Database\\Migrations\\Migration_database_optimizations','default','App',1724193997,1),
< (28,'20210422000001','App\\Database\\Migrations\\Migration_remove_duplicate_links','default','App',1724193997,1),
< (29,'20210714140000','App\\Database\\Migrations\\Migration_move_expenses_categories','default','App',1724193997,1),
< (30,'20220127000000','App\\Database\\Migrations\\Convert_to_ci4','default','App',1724193997,1),
< (31,'20230307000000','App\\Database\\Migrations\\IntToTinyint','default','App',1724193997,1),
< (32,'20230412000000','App\\Database\\Migrations\\Migration_add_missing_config','default','App',1724193997,1),
< (33,'20230412000001','App\\Database\\Migrations\\Migration_drop_account_number_index','default','App',1724193997,1),
< (34,'20240319000000','App\\Database\\Migrations\\Migration_Convert_Barcode_Types','default','App',1724193997,1),
< (35,'20240630000001','App\\Database\\Migrations\\Migration_fix_keys_for_db_upgrade','default','App',1724193998,1);
---
> (1,'20170501150000','App\\Database\\Migrations\\Migration_Upgrade_To_3_1_1','default','App',1724193746,1),
> (2,'20170502221506','App\\Database\\Migrations\\Migration_Sales_Tax_Data','default','App',1724193746,1),
> (3,'20180225100000','App\\Database\\Migrations\\Migration_Upgrade_To_3_2_0','default','App',1724193746,1),
> (4,'20180501100000','App\\Database\\Migrations\\Migration_Upgrade_To_3_2_1','default','App',1724193746,1),
> (5,'20181015100000','App\\Database\\Migrations\\Migration_Attributes','default','App',1724193746,1),
> (6,'20190111270000','App\\Database\\Migrations\\Migration_Upgrade_To_3_3_0','default','App',1724193746,1),
> (7,'20190129212600','App\\Database\\Migrations\\Migration_IndiaGST','default','App',1724193746,1),
> (8,'20190213210000','App\\Database\\Migrations\\Migration_IndiaGST1','default','App',1724193746,1),
> (9,'20190220210000','App\\Database\\Migrations\\Migration_IndiaGST2','default','App',1724193746,1),
> (10,'20190301124900','App\\Database\\Migrations\\Migration_decimal_attribute_type','default','App',1724193746,1),
> (11,'20190317102600','App\\Database\\Migrations\\Migration_add_iso_4217','default','App',1724193746,1),
> (12,'20190427100000','App\\Database\\Migrations\\Migration_PaymentTracking','default','App',1724193746,1),
> (13,'20190502100000','App\\Database\\Migrations\\Migration_RefundTracking','default','App',1724193746,1),
> (14,'20190612100000','App\\Database\\Migrations\\Migration_DBFix','default','App',1724193746,1),
> (15,'20190615100000','App\\Database\\Migrations\\Migration_fix_attribute_datetime','default','App',1724193746,1),
> (16,'20190712150200','App\\Database\\Migrations\\Migration_fix_empty_reports','default','App',1724193746,1),
> (17,'20191008100000','App\\Database\\Migrations\\Migration_receipttaxindicator','default','App',1724193746,1),
> (18,'20191231100000','App\\Database\\Migrations\\Migration_PaymentDateFix','default','App',1724193746,1),
> (19,'20200125100000','App\\Database\\Migrations\\Migration_SalesChangePrice','default','App',1724193746,1),
> (20,'20200202000000','App\\Database\\Migrations\\Migration_TaxAmount','default','App',1724193746,1),
> (21,'20200215100000','App\\Database\\Migrations\\Migration_taxgroupconstraint','default','App',1724193746,1),
> (22,'20200508000000','App\\Database\\Migrations\\Migration_image_upload_defaults','default','App',1724193746,1),
> (23,'20200819000000','App\\Database\\Migrations\\Migration_modify_attr_links_constraint','default','App',1724193746,1),
> (24,'20201108100000','App\\Database\\Migrations\\Migration_cashrounding','default','App',1724193746,1),
> (25,'20201110000000','App\\Database\\Migrations\\Migration_add_item_kit_number','default','App',1724193746,1),
> (26,'20210103000000','App\\Database\\Migrations\\Migration_modify_session_datatype','default','App',1724193746,1),
> (27,'20210422000000','App\\Database\\Migrations\\Migration_database_optimizations','default','App',1724193746,1),
> (28,'20210422000001','App\\Database\\Migrations\\Migration_remove_duplicate_links','default','App',1724193746,1),
> (29,'20210714140000','App\\Database\\Migrations\\Migration_move_expenses_categories','default','App',1724193746,1),
> (30,'20220127000000','App\\Database\\Migrations\\Convert_to_ci4','default','App',1724193879,2),
> (31,'20230307000000','App\\Database\\Migrations\\IntToTinyint','default','App',1724193879,2),
> (32,'20230412000000','App\\Database\\Migrations\\Migration_add_missing_config','default','App',1724193879,2),
> (33,'20230412000001','App\\Database\\Migrations\\Migration_drop_account_number_index','default','App',1724193879,2),
> (34,'20240319000000','App\\Database\\Migrations\\Migration_Convert_Barcode_Types','default','App',1724193879,2),
> (35,'20240630000001','App\\Database [...]

2024-08-20 23:18 UTC, jekkos commented
Also for some reason the person_id is not a primary key in the clean install.

2024-08-26 08:05 UTC, objecttothis requested changes
Some are just comments but we should come to an agreement on whether it's OK to pass a migration when it's changes fail before merging it as is.

2024-08-26 08:05 UTC, objecttothis commented on app/Database/Migrations/20210422000000_database_optimizations.php
> +		$result = $this->db->query('SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = \'' . $this->db->getPrefix() . "$table' AND index_name = '$index'");
@jekkos this is what I meant by doing a check to see if the index exists and deleting/recreating if it does.  If you want to move this to a new migration, that's fine, but like you said, it means removing the DROP statements from the SQL.

2024-08-26 08:05 UTC, objecttothis commented on app/Database/Migrations/20240630000001_fix_keys_for_db_upgrade.php
> +
OK, I see you already transferred it.

2024-08-26 08:05 UTC, objecttothis commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> +ALTER TABLE `ospos_items` DROP FOREIGN KEY `ospos_items_ibfk_1`;
I think the best way to bring both versions back into alignment is to do a check in the up() function to see if the (item_id, deleted) key exists and add it if it doesn't.

2024-08-26 22:10 UTC, jekkos commented on app/Database/Migrations/20210422000000_database_optimizations.php
> +		$result = $this->db->query('SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = \'' . $this->db->getPrefix() . "$table' AND index_name = '$index'");
I have removed the DROP only. The new keys will be created w/o name then and thus named 'PRIMARY'

2024-08-26 22:44 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> +ALTER TABLE `ospos_items` DROP FOREIGN KEY `ospos_items_ibfk_1`;
moved it to the new migration now

2024-08-26 22:44 UTC, jekkos commented on app/Database/Migrations/20170502221506_sales_tax_data.php
> +			return 0;
let's tackle this in the new PR

2024-08-26 22:45 UTC, closed without merging