Ci4 migration fixes
opensourcepos/opensourcepos pull request #4049
Opened 2024-08-26 22:43 UTC by jekkos

made yet another PR and squashed some commits, to make the actual diffs now more clear. Some changes that were done in 3.4 optimizations were moved to the more recent migration script instead.

2024-08-26 22:46 UTC, jekkos commented
One last thing to 
* check is the 3.3.9 -> 3.4 upgrade 
* clean db install seems to work
* substitute the error log with throwing an exception

2024-08-27 21:37 UTC, jekkos commented
now interesting observation I was testing my last change in the migration which stopped the process, resent the login submission and then found this in the database dump
 
```
  KEY `definition_name` (`definition_name`),
  KEY `definition_type` (`definition_type`),
  KEY `definition_name_2` (`definition_name`),
  KEY `definition_type_2` (`definition_type`),
  KEY `definition_name_3` (`definition_name`),
  KEY `definition_type_3` (`definition_type`),
```

This might explain the attribute key count error I saw some time ago

2024-09-06 23:07 UTC, jekkos commented
@objecttothis I have done one last comparison between 3.3.9 upgrade and fresh install, and only found that in the upgraded version we have an extra index in items table on item_id and deleted. This index is not present in the fresh install. I have added the delete statement back to align both schemas as you requested.

I'm not sure why the index was removed but I suppose that adding the deleted flag does not add a lot of performance benefits as typically a user won't have too many deleted items anyway.

Unless someone objects I would merge this and continue.

2024-09-06 23:10 UTC, objecttothis commented
No objections. I can do a code review Monday or Tuesday unless someone else gets to it first.

2024-09-10 10:20 UTC, objecttothis commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> +ALTER TABLE `ospos_items` DROP FOREIGN KEY `ospos_items_ibfk_1`;
This is a problem because it's also being dropped on line 119, so the second time you drop it, it creates an error.

2024-09-10 10:21 UTC, objecttothis commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> +ALTER TABLE `ospos_items` DROP FOREIGN KEY `ospos_items_ibfk_1`;
It looks like in the shuffle of merging @SteveIreland 's changes and mine, possibly some duplicates were created.  I thought I had sorted these per table, but perhaps I'm wrong.

2024-09-10 11:54 UTC, objecttothis requested changes

2024-09-10 11:54 UTC, objecttothis commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
line 11 fails for me on an existing database. The problem is that I can't find anywhere in the code where this constraint is being created besides here.  My theory is that I somehow added it to the existing database and then now I'm trying to run this migration script against it. I do have a pre-3.2.2 database which does not have the constraint.  If my guess here is wrong though, other people will have this line fail on them.  If that's the case then we will need to pull this out of here and move it to the PHP file where we can easily check to see if the constraint exists and only try to add it if it does.  T-SQL has an easy way to wrap SQL in an if statement, but MySQL is jenky and won't let you do it so you have to do it programmatically using QueryBuilder in PHP.

2024-09-10 21:24 UTC, jekkos commented on app/Database/Migrations/20190129212600_indiagst.php
> +			error_log('Tax rate migration failed due to severe errors.  Tax jurisdictions will need to be cleaned up manually');
@SteveIreland is this really a severe error? In case the default jurisdiction is not in the db, we might assumed the user is not using any of the specific tax features and we skip the migration? Or we just recreate the Jurisdiction and continue?

2024-09-10 22:28 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
@objecttothis I tried both clean install and install of 3.3.9 then upgrade to 3.4, without issues. But I must admit that at some point I also saw this attribute links unique error on dev. I have not been able to reproduce since then

2024-09-10 22:32 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> +ALTER TABLE `ospos_items` DROP FOREIGN KEY `ospos_items_ibfk_1`;
indeed the chnage was removed then added again , and now removed

2024-09-11 05:45 UTC, objecttothis commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
@jekkos During my testing of a clean database when I got errors, sometimes clearing the database and starting again made them go away.  This makes me think that perhaps the transactions are not working correctly or are only applying in a certain way.  For example, I noticed that if a script failed, then I made an adjustment and attempted to re-run it, I would get a different error that only happened if part of the previous script had actually been applied.  I wonder if this is how and when we fail the migration will cause this.

2024-09-15 21:51 UTC, jekkos commented on app/Database/Migrations/20190129212600_indiagst.php
> +			error_log('Tax rate migration failed due to severe errors.  Tax jurisdictions will need to be cleaned up manually');
@SteveIreland @objecttothis I have searched the codebase for jurisdiction id but do not find any defaults there, so this case might be a perfectly valid one? Can we remove the check and error message?

2024-09-15 21:52 UTC, jekkos commented on app/Database/Migrations/20190129212600_indiagst.php
> +			error_log('Tax rate migration failed due to severe errors.  Tax jurisdictions will need to be cleaned up manually');
Also I wonder if the query returns no results, then getRow()->jurisdiction_id will probably already craash the script so the extra check can only fail if the schema does not contain the column at this point.

2024-09-15 21:58 UTC, jekkos commented on app/Database/Migrations/20190129212600_indiagst.php
> +			error_log('Tax rate migration failed due to severe errors.  Tax jurisdictions will need to be cleaned up manually');
@objecttothis This failure case is limited to what is executed in this method here directly. I believe the case just handles the fact that the insert query that ran before it failed, which I think should not happen. So maybe it's all fine here.

2024-09-15 22:02 UTC, jekkos commented on app/Database/Migrations/20190129212600_indiagst.php
> +			error_log('Tax rate migration failed due to severe errors.  Tax jurisdictions will need to be cleaned up manually');
@objecttothis we can just remove this clause as it will be unlikely that we end up in this situation, unless the table structure is not created as it should. And in that case I agree we should probably stop the migration and fix the bug.

2024-09-15 22:04 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
I guess that indeed the migrations do not run transactionally, so indeed if something goes wrong, you might end up with a half baked database schema which you can then try to migrate by running the migration again.
So I guess most of the time things that were already applied will error out and can be ignored..

2024-09-15 22:10 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
https://github.com/prisma/prisma/discussions/3774

2024-09-15 22:12 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
We can just wrap this statement in an exists and then it should be fine no?

2024-09-15 22:15 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
@objecttothis I see this contraint was already defined in the `3.3.0_attributes.sql`, check line 33

2024-09-15 22:20 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
The funny thing is that my db dumps contains those two constraints, but they are actually the same thing
```
  UNIQUE KEY `attribute_links_uq1` (`attribute_id`,`definition_id`,`item_id`,`sale_id`,`receiving_id`),
  UNIQUE KEY `attribute_links_uq2` (`item_id`,`sale_id`,`receiving_id`,`definition_id`,`attribute_id`),
```
So perhaps some setting in MySql causes it to error out on this. In my case it did not bother and did just recreate the constraint with the same fields but in different order

2024-09-15 22:21 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
Did a new push that removes this line

2024-09-16 10:18 UTC, objecttothis approved these changes

2024-09-16 12:18 UTC, merged

2024-09-16 15:23 UTC, jekkos commented on app/Database/Migrations/20170502221506_sales_tax_data.php
> +		if(!$result)
@SteveIreland was there particular reason to add the false check? 
Do we need to take the only_full_group thing into account here? Perhaps that is the reason the query sometimes fails?

2024-09-16 15:23 UTC, jekkos commented on app/Database/Migrations/20200202000000_taxamount.php
> +			error_log('Database error in 20200202000000_taxamount.php related to sales_taxes or sales_items_taxes.');
also here, do we have any expected failures?

2024-09-20 06:18 UTC, objecttothis commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> The funny thing is that my db dumps contains those two constraints, but they are actually the same thing
> 
> ```
>   UNIQUE KEY `attribute_links_uq1` (`attribute_id`,`definition_id`,`item_id`,`sale_id`,`receiving_id`),
>   UNIQUE KEY `attribute_links_uq2` (`item_id`,`sale_id`,`receiving_id`,`definition_id`,`attribute_id`),
> ```
> 
> So perhaps some setting in MySql causes it to error out on this. In my case it did not bother and did just recreate the constraint with the same fields but in different order

They are not the same constraint.  They contain the same columns but the order of the constraint matters.  These were created because they are the best indexes for slow running queries in one or more of the models.

2024-09-20 06:30 UTC, objecttothis commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> I guess that indeed the migrations do not run transactionally, so if something goes wrong then you will end up with a half baked database schema which you can then try to migrate by running the migration again. So I guess most of the time things that were already applied will error out and can be ignored..

I was kind of surprised to learn this since I thought they did run in a transaction.  IMO we should wrap all the migrations in a transStart() / transComplete() so that they do run transactionally.  As is, it results in inconsistent schemas in the event of a migration failure.  I can't think of anything that would cause this to be a breaking change, can you?

2024-09-20 06:53 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
that might be a bot of work as there are certainly queries now that we allow to fail and still proceed the migration. All of this will need to be reviewed and handled. But I agree it is probably the more correct way of working and we will get a lot more bug reports related to uograde failures

2024-09-20 06:55 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> > The funny thing is that my db dumps contains those two constraints, but they are actually the same thing
> > ```
> >   UNIQUE KEY `attribute_links_uq1` (`attribute_id`,`definition_id`,`item_id`,`sale_id`,`receiving_id`),
> >   UNIQUE KEY `attribute_links_uq2` (`item_id`,`sale_id`,`receiving_id`,`definition_id`,`attribute_id`),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So perhaps some setting in MySql causes it to error out on this. In my case it did not bother and did just recreate the constraint with the same fields but in different order
> 
> They are not the same constraint. They contain the same columns but the order of the constraint matters. These were created because they are the best indexes for slow running queries in one or more of the models.

I do have the impression that some MySQL versions do not consider these constraints to be different, hence the upgrade failure

2024-09-20 06:59 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
So the index is indeed where the order matters. For the unique constraint, the order does not matter. We could convert the second constraint to an index then if it is really needed.

2024-09-24 07:22 UTC, objecttothis commented on app/Database/Migrations/sqlscripts/3.4.0_database_optimizations.sql
> that might be a lot of work as there are certainly queries now that we allow to fail and still proceed the migration. All of this will need to be reviewed and handled. But I agree it is probably the more correct way of working and we will get a lot more bug reports related to uograde failures

I can take a look into this, but perhaps as a feature to be released after 3.4.0. I agree that this may lead to more bug reports, but that's not because the bugs didn't exist before... people just weren't aware of them.