Fix company logo overwrite
opensourcepos/opensourcepos pull request #4061
Opened 2024-09-19 23:32 UTC by jekkos

2024-09-24 06:55 UTC, objecttothis commented
Reviewing now.

2024-09-24 07:09 UTC, objecttothis requested changes

2024-09-24 07:09 UTC, objecttothis commented on app/Controllers/Config.php
> +			$filename = md5(date('Y-m-d H:i:s:u'));
Looks like you're assigning `$filename` here, but I don't see where you are using it.

2024-09-24 07:09 UTC, objecttothis commented on app/Controllers/Items.php
> +			'raw_name' => md5(date('Y-m-d H:i:s:u')),
Did you decide against using a hash of filename + datestamp? It's not in a foreach/while loops, so I guess the only way for a duplicate is if two different sessions ran this line in the same microsecond. Not a likely scenario, but not impossible. I don't feel strongly about it.

2024-10-02 22:01 UTC, jekkos commented
Comments were addressed but I shuold do a short retest

2024-10-05 23:53 UTC, jekkos commented
Comments addressed , tested locally and seems fine, will merge.

2024-10-05 23:53 UTC, merged