Fixed sales item suggestion by location
opensourcepos/opensourcepos pull request #4065
Opened 2024-09-22 19:21 UTC by ri-cky

2024-09-22 20:34 UTC, jekkos commented on .github/workflows/new-build-image.yml
> +    runs-on: ubuntu-latest
Cool you are using github actions here to build the project? #2834

2024-09-22 20:36 UTC, jekkos requested changes

2024-09-22 20:36 UTC, jekkos commented on application/models/Item.php
> +	public function get_search_suggestions($search, $filters = array('is_deleted' => FALSE, 'search_custom' => FALSE, 'location' => NULL), $unique = FALSE, $limit = 25)
this is probably the change you wanted to submit? but the changeset seems to be made against old 3.3.9. Currently we only accept contributions against master branch which has moved to CI4.

2024-09-22 20:36 UTC, jekkos commented on application/models/Item.php
> +	public function get_search_suggestions($search, $filters = array('is_deleted' => FALSE, 'search_custom' => FALSE, 'location' => NULL), $unique = FALSE, $limit = 25)
should not be so hard to port it to the master branch, if you feel up to that, then that would be great!

2024-09-24 21:32 UTC, ri-cky commented
@MalikAbiola Please check the comment and conflict in this PR

2024-09-25 21:20 UTC, closed without merging

2024-09-25 21:20 UTC, ri-cky commented on application/models/Item.php
> +	public function get_search_suggestions($search, $filters = array('is_deleted' => FALSE, 'search_custom' => FALSE, 'location' => NULL), $unique = FALSE, $limit = 25)
I will try to do that and make a fresh PR