Bugfix Attributes not saving
opensourcepos/opensourcepos pull request #4080
Opened 2024-09-30 11:06 UTC by objecttothis

2024-10-08 12:46 UTC, objecttothis commented
I think I'm closer to a fix here but I'm out of time for the day.  In the Items controller the saveItemAttributes function is pulling attributeIds for all the attributes submitted in the form:
```$attributeIds = $this->request->getPost('attribute_ids');```

On a new DATE `definitionType` an attributeId of -1 is sent.  I think this means it's a new attribute, but I need to confirm this.  The problem is that in the Attribute model the if statement which checks if it's a new attribute or not is checking for an empty attribute_id (0, null or false).  If, indeed, -1 equals new, then we should also add a check to 
```
		//New Attribute
		if(empty($attribute_id) || empty($item_id))
		{
```
so that it also looks for -1 attribute_ids.  Something like
```
		//New Attribute
		if(empty($attribute_id)
                    || $attribute_id === NEWATTRIBUTE
                    || empty($item_id))
		{
```
The problem is that when I do this, it pukes.  I think the culprit might be Attribute::attributeValueExists().  I need to step through it with a debugger on a date and see what it does because it's what is returning -1 rather than false.

2024-10-22 16:49 UTC, jekkos commented
Would it be possible to squash the history here? Seems like a lot of old commits were dragged in for some reason

2024-10-22 16:53 UTC, objecttothis commented
I think our current process is to do a squash and merge rather than merge the commits without squash. Is that different from what you're asking? I suspect the commits got dragged in when I did a rebase on the master. Is there a better way to do that?

2024-10-22 16:53 UTC, jekkos requested changes
I appreciate the work as always! I do have some remarks on the only_full_group_by and unique_constraint for item and definition_id.

2024-10-22 16:53 UTC, jekkos commented on app/Database/Migrations/20240826000000_fix_duplicate_attributes.php
> +		$builder->select('item_id, definition_id, MIN(attribute_id) as attribute_id');
will this query work with the only_full_group_by enabled?

2024-10-22 16:53 UTC, jekkos commented on app/Database/Migrations/sqlscripts/3.4.0_attribute_links_unique_constraint.sql
> +	ADD COLUMN `generated_unique_column` VARCHAR(255) GENERATED ALWAYS AS (
At work we recently faced some issues with some of these generated columns.. at first it seems like a nice feature but it hits you back once you want to migrate the database schema.

It might also have an impact on the Mysql versions can be used. From which version on is this generated column supported? Does it also work on MariaDB and yes what is the minimum version there? Documentation might need to be updated for this.

2024-10-22 16:53 UTC, jekkos commented on app/Models/Attribute.php
> +				$data_type				= 'date';
glad to see this simplification!

2024-10-22 17:18 UTC, objecttothis commented on app/Database/Migrations/20240826000000_fix_duplicate_attributes.php
> +		$builder->select('item_id, definition_id, MIN(attribute_id) as attribute_id');
Yes, because my dev database has `ONLY_FULL_GROUP_BY` enabled in the sql_mode and it didn't puke during testing.

2024-10-22 17:20 UTC, objecttothis commented on app/Database/Migrations/sqlscripts/3.4.0_attribute_links_unique_constraint.sql
> +	ADD COLUMN `generated_unique_column` VARCHAR(255) GENERATED ALWAYS AS (
According to copilot they are supported from MySQL: Starting from version 5.7 and MariaDB: Starting from version 10.2. If there is another way to enforce uniqueness, I'm happy to explore it.

2024-10-22 17:22 UTC, objecttothis commented on app/Models/Attribute.php
> +				$data_type				= 'date';
yay for refactoring out duplicate code blocks!

2024-10-31 23:05 UTC, jekkos commented
I'll rebase the PR otherwise this weekend.

2024-11-04 06:55 UTC, objecttothis commented
@jekkos is the only issue with this PR that the commit history is messy?  It seems that the method I'm using for rebasing on the master is causing the messy commit history.  Within PHPStorm I go to git > fetch all remotes > right-click origin/master > rebase 'X' onto 'origin/master'. I let it replay the commit history. When it comes to a conflict, I select the code changes from my code and continue the rebase. At the end I push the commits generated from resolving conflicts during the rebase operation.  Should I be doing this differently?  If not and it's normal to need to clean up commit history, what is the best way to see the commit history and clean it up. I'm generally not used to using git through the command line, so bonus if there is a GUI method.  

Also, usually when I merge a PR, I squash and merge rather than just merge.  I could clean up the commit messages there as those tend to be concatenated together.

2024-11-04 23:02 UTC, jekkos commented
Ah right I just meant squash the history as it seems this has some duplicate commit messages that are already in master. So if you can squash the old commits out at the end then that is fine as well. Typically I do this on the command line before I make the PR, but doing it here can be convenient.

2024-11-05 12:07 UTC, objecttothis commented
> Ah right I just meant squash the history as it seems this has some duplicate commit messages that are already in master. So if you can squash the old commits out at the end then that is fine as well. Typically I do this on the command line before I make the PR, but doing it here can be convenient.

Yes, I will do this at the end but it won't allow me to squash and merge unless I get a code review approval.  I can override it but I prefer not to get in that habit.

2024-11-05 21:36 UTC, jekkos approved these changes
Sorry I thought I already approved it, didn't mean to block

2024-11-05 21:37 UTC, merged